### ISSUE TITLE
Contributing.md needs further work to remove anything specific to ublue's startingpoint

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#10]
example: jorge's email

**Comment by RoyalOughtness** [comment]
+ PR guidelines should be modified to clarify what a PR description should include

**Comment by wandapeter** [comment]
> example: jorge's email

Until we have a better solution we could just say people should open an issue instead of writing an email.

> * PR guidelines should be modified to clarify what a PR description should include

What should those guidelines include?

Off the top of my head:

- Create an issue with the problems
  - Create PR and reference issue
- Give a short and cohesive explanations to the changes
- Follow Code and Commit guidelines

Something like that?

**Comment by RoyalOughtness** [comment]
> > example: jorge's email
> 
> Until we have a better solution we could just say people should open an issue instead of writing an email.
> 
> > * PR guidelines should be modified to clarify what a PR description should include
> 
> What should those guidelines include?
> 
> Off the top of my head:
> 
> * Create an issue with the problems
>   
>   * Create PR and reference issue
> * Give a short and cohesive explanations to the changes
> * Follow Code and Commit guidelines
> 
> Something like that?

that looks good, and also: include test results and screenshots if relevant to your change on top of having a passing build

**Comment by RoyalOughtness** [comment]
@34N0 also, putting all changes in a PR into a single commit. also that PRs should have a clear scope. the usual stuff.

**Comment by wandapeter** [comment]
pr guidelines added in 9833fe4
