### ISSUE TITLE
Use DNS over https by default

### ISSUE THREAD

**Issue by ArtikusHG** [secureblue/secureblue#118]
I believe it would be a great addition to the images if DoH was used by default. Regular DNS is highly insecure and can be subject to many types of attacks. Making use of DoH should be easy (adding a config file to /etc), since Fedora already uses systemd-networkd by default. If you consider this in scope, I am willing to make a PR.

**Comment by RoyalOughtness** [comment]
@ArtikusHG Yes, this is in-scope as it not only provides privacy improvements but security improvements as well (by preventing tampering).

A PR would be appreciated on this. Ideally, it would not depend on or hardcode any specific DNS service. It should just use DoH if the network-provided service makes it available. I'm not familiar with systemd-networkd configuration, so I'll leave it up to you whether this is possible.

**Comment by ArtikusHG** [comment]
@qoijjj sadly we will have to choose which specific DNS providers to use. However, the good news is that this won't affect usability, since we can choose fallbacks (so if the main one we chose doesn't work, the query goes through the other one, then the other one and so on; and if all the providers on the list fail we probably have bigger problems).

What we'd have to do is add is something like this to ```/etc/systemd/resolved.conf```:

```
[Resolve]
DNS=9.9.9.9#dns.quad9.net 1.1.1.1#cloudflare-dns.com
DNSOverTLS=yes
DNSSEC=yes
FallbackDNS=8.8.8.8 1.0.0.1 8.8.4.4
```

In this example I only have two providers, but multiple can be added. I think we should include the ones that have a no-logging policy first (Quad9, Mullvad, etc.), and then include the ones that do some logging, but have higher uptime (Google, CloudFlare) as a fallback if all the good ones fail catastrophically.

**Comment by RoyalOughtness** [comment]
@ArtikusHG I'm less worried about usability and more about being too opinionated. GrapheneOS for example sets "Private DNS" (what they call DoH) to "Automatic" by default. This makes it so the DNS provider is still served from the network, but DoH is enabled if it's provided by the network. We should look into getting feature parity with what GrapheneOS does first, if at all possible.

If this isn't possible, then instead of baking this into the image, please add a `just` command like ```just set-cloudflare-doh``` that allows users to set this easily if they wish. Then please add a yafti prompt informing the user that this is available and what the security advantages are.

>  no-logging policy first 

Reminder that anything privacy related is not in scope. We should prioritize providers that have good security posture and ideally provide security audits publicly. A secure, major provider that logs is preferred to a more "dodgy" provider that claims to not log.

**Comment by ArtikusHG** [comment]
> Reminder that anything privacy related is not in scope. We should prioritize providers that have good security posture and ideally provide security audits publicly. A secure, major provider that logs is preferred to a more "dodgy" provider that claims to not log.

Quad9 does have security audits and so does Mullvad. They also publish transparency reports and have been around for quite a long time. They are not "dodgy" providers.

As per network DoH, I will look into that, but I am not sure whether that's possible. If it is though, I will make my PR with that, if not, I'll do your suggestion with just/yafti

**Comment by RoyalOughtness** [comment]
> They are not "dodgy" providers.

Agreed, I didn't mean to imply any particular provider. I was just saying as a general rule, security audits are more important than logging policy.

> As per network DoH, I will look into that, but I am not sure whether that's possible. If it is though, I will make my PR with that, if not, I'll do your suggestion with just/yafti

Great, thank you

**Comment by wandapeter** [comment]
Hello @ArtikusHG :smile: 

Maybe we could just use the GrapheneOS DNS serers? I haven't looked into this and just had the idea. There's this GOS article listing their servers:
https://grapheneos.org/articles/grapheneos-servers

**Comment by ArtikusHG** [comment]
Hey @34N0 that is a great idea! I'm a bit busy right now but when I'm back on track I will try to implement that

**Comment by Sadoon-AlBader** [comment]
> Maybe we could just use the GrapheneOS DNS serers? I haven't looked into this and just had the idea. There's this GOS article listing their servers: https://grapheneos.org/articles/grapheneos-servers

Apparently those seem to be specific to GOS services? I'm not entirely sure but I've tried using them on GrapheneOS itself and I can't get internet.

**Comment by RoyalOughtness** [comment]
> > Maybe we could just use the GrapheneOS DNS serers? I haven't looked into this and just had the idea. There's this GOS article listing their servers: https://grapheneos.org/articles/grapheneos-servers
> 
> Apparently those seem to be specific to GOS services? I'm not entirely sure but I've tried using them on GrapheneOS itself and I can't get internet.

It doesn't look like they support recursive queries for some reason:

```
$ dig @51.222.14.6 google.com

; <<>> DiG 9.18.20 <<>> @51.222.14.6 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 59745
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available
```

**Comment by RoyalOughtness** [comment]
upon browsing the [arch docs](https://wiki.archlinux.org/title/systemd-resolved#DNS_over_TLS) I discovered the following configuration option that may be relevant to this issue:

`DNSOverTLS=opportunistic`

If set, resolved will automatically use DNSOverTLS if it's available, otherwise it will fall back to regular DNS. So if the user has configured a DNS on their router that supports DNSOverTLS, it will be used. 

This allows us to support DOT without being opinionated in which DNS server is used and without changing the source of the DNS provider from the local router to the image.

**Comment by RoyalOughtness** [comment]
Made this change and verified using ngrep that DNSOverTLS and DNSSEC are used if the network's nameserver (or configured override) supports either or both, respectively:

https://github.com/secureblue/secureblue/commit/a374ce5ae9f302f9db46e4fa33b94beafd36c2ba

**Comment by ghost** [comment]
It might be a good idea to support adding DoH too because my school for example blocks DoT and I am forced to use their unencrypted DNS. Dnscrypt-proxy seems to be broken on secureblue and WG configs are somehow blocked too, even tho it works on my phone.
