### ISSUE TITLE
hardened_malloc configured incorrectly

### ISSUE THREAD

**Issue by SkewedZeppelin** [secureblue/secureblue#119]
https://github.com/secureblue/secureblue/blob/6de57116655e9a5844d9b194130d8351fcfc417f/config/files/usr/etc/ld.so.preload#L1

Please see https://gist.github.com/SkewedZeppelin/7f293d64c1c651bdc21526519d9e192b

**Comment by RoyalOughtness** [comment]
@SkewedZeppelin thank you for bringing this issue to my attention.

To summarize the issue to make sure I understand each point:

> the library should be chmod 644 instead of 755

this makes sense

> the library should have suid set

It's not clear at all why this would be desirable. From the docs you referenced, it seems like "secure execution mode" is actually something we want to avoid if at all possible. It's something that the linker enables if there's something suspicious about the target library:

> For security reasons, the effects of some environment variables are voided or modified if the dynamic linker determines that the binary should be run in secure-execution mode.

> The process's real and effective user IDs differ, or the real and effective group IDs differ. This typically occurs as a result of executing a set-user-ID or set-group-ID program.

~~This makes sense because a setuid library being loaded exposes privesc. Setting the setuid flag on hardened_malloc to trigger secure execution mode is therefore akin to starting a fire to get the fire alarm to go off. If I understand this correctly, the divestedcg rpm is configured incorrectly and dangerously by setting the setuid bit: https://github.com/divestedcg/rpm-hardened_malloc/blob/master/hardened_malloc.spec#L87~~

> In secure-execution mode, preload pathnames containing slashes are ignored.

This seems fine since secure execution mode should be avoided anyways, however this may explain why electron apps are ignoring it. For that reason it may be valuable to remove the directory prefix.

**Comment by SkewedZeppelin** [comment]
You're misreading it. It does not give the library any special permissions or change anything itself.

If you run eg. sudo with your package it'll spam errors.

**Comment by RoyalOughtness** [comment]
> You're misreading it. It does not give the library any special permissions or change anything itself.

Sure but what is it accomplishing then? Why are you setting it?

**Comment by SkewedZeppelin** [comment]
@qoijjj
so that it actually works on privileged programs, otherwise it isn't loaded at all

this is covered in the gist.

**Comment by RoyalOughtness** [comment]
> @qoijjj so that it actually works on privileged programs, otherwise it isn't loaded at all
> 
> this is covered in the gist.

I see, you're right I was misreading this. Thanks for clarifying, I will make the necessary changes as soon as I can. If you want, feel free to send a PR.

**Comment by SkewedZeppelin** [comment]
its already fixed in the package you forked from, you can cherrypick it: https://github.com/rusty-snake/fedora-extras/commit/2b666b849b513b245fac606d319ffb8f1e293437

**Comment by RoyalOughtness** [comment]
> its already fixed in the package you forked from, you can cherrypick it: [rusty-snake/fedora-extras@2b666b8](https://github.com/rusty-snake/fedora-extras/commit/2b666b849b513b245fac606d319ffb8f1e293437)

Oh perfect, I'll just pull that in and rebuild. Thanks!

As for the ld.so.preload change, that seems pretty straightforward. I assume it works without the /usr/lib64 prefix with no additional changes because it already looks in /usr/lib64 by default?

**Comment by RoyalOughtness** [comment]
also, @SkewedZeppelin it looks like the switch to 644 wasn't made here? https://github.com/qoijjj/fedora-extras/commit/2b666b849b513b245fac606d319ffb8f1e293437

**Comment by RoyalOughtness** [comment]
This should be functional now, the chmod settings should get updated upstream in the repo from rusty-snake which I'll pull in to my fork (which just makes it copr compatible)

**Comment by RoyalOughtness** [comment]
@SkewedZeppelin can we get removed from your permissions.md? :smile: 

Also, I saw on that file that there's new considerations as of 12/12. Can you elaborate more on what you're looking into? Thanks.
