### ISSUE TITLE
Revoke unsafe flatpak permissions by default

### ISSUE THREAD

**Issue by starkle** [secureblue/secureblue#125]
Currently, a fundamental flaw with flatpak is that apps decide which permissions they are granted. This makes the permission model basically pointless because flatpaks are still fully trusted. Commonly requested permissions also trivially allow running code and scripts with user privileges outside the sandbox, such as `filesystem=home` [1], `device=all` [2], and `talk-name=org.freedesktop.Flatpak` [3].

Users can manually revoke permissions before running an app for the first time, but this is tedious and prone to error if you don't know what you're doing. Also, flatpaks can change their permissions when being updated, so this process has to be repeated frequently. Ideally it would be more like Android, where unsafe permissions are not granted by default, each requiring confirmation from the user with appropriate warnings.

Adding global overrides gets somewhat closer to this, shifting things to more of an opt-in model. For example, running `flatpak override --user --nodevice=all` will nullify the /dev attack surface until the user opts into it with a per-app override. This also protects the user if an app originally didn't request the permission, then tries to through an update.

This is what I personally do, although I'm not an expert:
- Revoke all shares, sockets, devices, and features by default unless determined to be safe like `wayland` and `fallback-x11`.
- Revoke well-known unsafe busses by default like `org.freedesktop.Flatpak`.
- Revoke the `host` and `home` filesystems by default because they are broad, unsafe, and often not necessary.

However, there are some problems with this proposal:
- It's partially a form badness enumeration. For example, a flatpak could instead declare `filesystem=~` and get the same access as `filesystem=home`. Any directories that are not well-known can't be reliably blocked with this proposal. It's similarly hard to know which of all the session and system busses are unsafe.
- It will cause apps to break, which may be annoying.
- Because of the above, manual review is still necessary to revoke some permissions, as well as to grant others to fix breakage, so the tediousness may not be significantly reduced.
- Permission managers like the KDE KCM may list the revoked permissions on all apps, even if they never requested it. This could lead users trying to fix breakage to accidentally enable the wrong unsafe permission.

Still, I think providing these overrides is an important harm reduction measure. I also think that making users encounter breakage is a good thing. Forcing users to opt-in to unsafe permissions will better educate them on what access a program has, and hopefully lead them to pressure app developers to actually support being sandboxed.

[1] https://madaidans-insecurities.github.io/linux.html#flatpak
[2] https://hanako.codeberg.page
[3] https://github.com/flatpak/flatpak/issues/5161

**Comment by RoyalOughtness** [comment]
Thanks for opening this issue. I'll respond point by point while avoiding the specifics about specific permissions.

> a fundamental flaw with flatpak is that apps decide which permissions they are granted. 

This is not true. There are two false assumptions in that statement:

1. Flatpak is granting permissions to apps that would otherwise not would have them

This is false. A flatpak can at worst grant the same permissions to an app that an unsandboxed rpm would have.

2. Apps decide what permissions they get.

This is also false because it's missing a word. Apps decide what permissions they get by **default**. This is true of an rpm as well in terms of what its chown and chmod values are set to. The user of course can change them, and it's arguably even easier to change them for flatpaks since you can use flatseal.

>  because flatpaks are still fully trusted. 

This is again not true. They are trusted only insofar as they provide their default sandbox permissions. This is not "full" in any sense of the word "fully". If they were fully trusted, I wouldn't be able to change the permissions.

> Users can manually revoke permissions before running an app for the first time, but this is tedious and prone to error if you don't know what you're doing. 

This is true regardless of what the defaults are set to. If the defaults are too restrictive, a user who doesn't know what they're doing may just go open up random permissions in a desperate attempt to get the app running. Either way it's a matter of user education, and that's not in scope for this project.

> Ideally it would be more like Android, where unsafe permissions are not granted by default, each requiring confirmation from the user with appropriate warnings.

I agree completely, but this is an upstream improvement that flatpak itself needs to make. 

> flatpaks can change their permissions when being updated,

And flatpak tells you when they're doing so.

> Forcing users to opt-in to unsafe permissions will better educate them on what access a program has, and hopefully lead them to pressure app developers to actually support being sandboxed.

Introducing breakage as an educational tool is not desirable or in scope for this project. As I said above, it goes either way and is ultimately up to the user.

If you are concerned about an application having too many permissions by default, you should submit a pull request upstream for that app and start the discussion there about what permissions are really required out of the box. That's the best way forward we have until flatpak adopts an android-style permissions-popup model.

> https://madaidans-insecurities.github.io/linux.html#flatpak

Madaidan has some good hardening recommendations generally, but when it comes to flatpak his points don't make much sense. For one, his statement "It fully trusts the applications" is simply untrue as I elaborated above. Even if it were true, it would be true for any rpm as well. It's simply not a new issue relative to an rpm. 

Then on this point "This means that security is effectively optional and applications can simply choose not to be sufficiently sandboxed." it is true but misleading. Security **is** effectively optional. We are comparing different packaging formats, not comparing flatpaks to some packaging ideal. Flatpaks are sandboxed, rpms are not. Can the flatpak maintainers effectively disable the sandbox? Sure. Does that make flatpaks worse than an rpm? No. It puts them on par.

All of that is setting aside the fact that his article is largely out of date, and many flatpaks have since scaled down their permissions. 




In short, my points are as follows:

- Using flatpak is as a general rule an improvement on using an app completely unsandboxed (via an rpm for example)
- Configuring app permissions is up to the user, and user education is not in scope for this project. Even if it were, removing permissions that may cause breakage could have the opposite of the intended effect.
- We are already providing flatseal as the only default flatpak so that users are equipped by default to change permissions of their installed apps easily.
- We are already only enabling the flathub-verified remote by default so as to ensure that flatpak apps are only coming from the developers.
- Making improvements to flatpak's permissions model and improving the defaults for specific apps are both real changes that should be made, but they should be made upstream so that all users can benefit.

**Comment by starkle** [comment]
I appreciate the thorough response, and mostly agree with what you've said.

You made one wrong assumption that I think explains the disagreements:

> We are comparing different packaging formats, not comparing flatpaks to some packaging ideal.

I *am* comparing flatpaks to some ideal. To me that ideal is flatpaks with no permissions. From what I've read such programs are decently isolated. An ideal desktop system would sandbox its applications by default, similar to Android, which we seem to agree on. Flatpak might get close, but the glaring problem is its default behavior around permissions.

The threat model of sandboxing apps is to minimize the harm done by a malicious or compromised program. If an app happens to be malicious, it's a big problem to let it define what permissions it gets, especially when those permissions allow full sandbox escape. My proposed overrides solution partially remedies this, but not fully. Only allowing flathub-verified as you've done is another good step to avoid malware entirely.

While I still recommend people implement overrides as I've described, or at least manually review and harden every flatpak's permissions, I can see why this incomplete workaround for flatpak's design decisions is out of scope for secureblue.

**Comment by RoyalOughtness** [comment]
Thanks for your response. I agree with much of what you said, but I think it boils down to scope.

Should flatpaks be scoped down to as few permissions as they need to function? Yes

Would it be even better if permissions were granted directly by the user at runtime like in android? Yes

Is either of those a reason to abandon flatpak entirely? No

Is either of those in scope for this project? No

> I am comparing flatpaks to some ideal. 

[Perfect is the enemy of good.
](https://en.wikipedia.org/wiki/Perfect_is_the_enemy_of_good)  A perfectly secure system is one that doesn't exist at all. Interestingly, you captured this quite well in this statement:

> To me that ideal is flatpaks with no permissions.

Disabling all permissions would render the applications useless, and at that point you might as well not use the computer at all for security's sake.

> An ideal desktop system would sandbox its applications by default, similar to Android, which we seem to agree on. Flatpak might get close, but the glaring problem is its default behavior around permissions.

I agree, and there are three things that should happen to fix it:

1. The fastest change: users should configure permissions to their liking
2. A fast change: submit default permissions changes to upstream flatpaks at their repos.
3. A slow change: overhauling flatpaks to introduce a better permissions model

None of those things are in scope for the project, they are all upstream of this project. 

> My proposed overrides solution partially remedies this, but not fully. 

Like I mentioned earlier, I don't think it actually remedies it at all. Ultimately the issue we'd be trying to solve by globally overriding default permissions isn't really fixing flatpak, but preempting "bad" user behavior. This doesn't work because if breakage is introduced, a user who doesn't know to scope the permissions of their flatpaks down is the same type of user who would open up unnecessary permissions to get apps working. 

Until flatpak changes the permissions model, the solution here is to get more people to care and report unnecessary permissions to upstream projects. I think this would be a valuable initiative that I'd be happy to help with. Also important is getting apps to get [verified](https://flathub.org/apps/collection/verified/1).

What we would need to get started is a collaboration space in the form of a repo or repo wiki where we can keep a list of common flatpaks, their current permissions, and their minimal permissions required to function. And if those are different, especially if they're significantly different, we can propose changes upstream. If you put together that project, maybe something like "flatpak permissions audit", I'd be happy to help.

**Comment by starkle** [comment]
Fair points. I think you captured the current situation here:

> 1. The fastest change: users should configure permissions to their liking
> 2. A fast change: submit default permissions changes to upstream flatpaks at their repos.
> 3. A slow change: overhauling flatpaks to introduce a better permissions model

Option 3 is what I'd love to see, but of course none of these are in scope.

It's worth pointing out that I happily use a system with the unsafe permissions revoked for all apps. So it's not like a permission-less flatpak model provides a useless system like you suggest. I'm willing to tolerate some breakage here and there to achieve that, but it's not as much as you might think.

I agree that finding the "minimal permission" config for apps probably deserves its own project. I remember [this article](https://privsec.dev/posts/linux/desktop-linux-hardening/#flatpak) referencing two projects [1] [2] that attempt to do something like this.

Encouraging the upstream flatpaks to better support being sandboxed is also great idea. My concern is that upstream won't care to be sandboxed unless there is considerable push to.

If I were to start a project, it would probably be a resource/wiki encouraging people to implement overrides by default as I've proposed, and providing education on how to properly troubleshoot breakage. It seems that last part is the main concern we share.

I'll close this as not planned since it's out of scope.

[1] https://github.com/tommytran732/Flatpak-Overrides
[2] https://github.com/rusty-snake/kyst/tree/main/flatpak

**Comment by RoyalOughtness** [comment]
> It's worth pointing out that I happily use a system with the unsafe permissions revoked for all apps. So it's not like a permission-less flatpak model provides a useless system like you suggest. I'm willing to tolerate some breakage here and there to achieve that, but it's not as much as you might think.

"unsafe permissions revoked" is different from "To me that ideal is flatpaks with no permissions."  Permissionless would mean not even wayland or x11 permissions

> I agree that finding the "minimal permission" config for apps probably deserves its own project. I remember [this article](https://privsec.dev/posts/linux/desktop-linux-hardening/#flatpak) referencing two projects [1] [2] that attempt to do something like this.
> 
> If I were to start a project, it would probably be a resource/wiki encouraging people to implement overrides by default as I've proposed, and providing education on how to properly troubleshoot breakage. It seems that last part is the main concern we share.

To be clear, this isn't what I meant. A catalog of recommended overrides only helps the same type of people inclined to refine the permissions anyways. The only way to help all users is to submit upstream changes to the flatpaks. We would need a project that tracks not recommended permissions overrides, but tracks changes to flatpaks. It could even be something as simple as:

| Package Id      | Verified? | Unnecessary Permissions | Pull Requests |
| ----------- | ----------- | ----------- | ----------- |
|       |        |
|    |         | 

> Encouraging the upstream flatpaks to better support being sandboxed is also great idea. My concern is that upstream won't care to be sandboxed unless there is considerable push to.

I think you'd be surprised. I suspect some package maintainers just haven't bothered since no one has asked. Same thing goes for getting apps verified.

**Comment by starkle** [comment]
Sorry, I was hyperbolic when I described flatpaks with no permissions at all. The truth is that only some permissions allow for sandbox escape or are otherwise dangerous, which I'm calling "unsafe". The wayland socket is designed with security in mind, and is presumed to be a safe permission that does not allow sandbox escape. Others like the X11 permission allow sandbox escape by design, and should be considered unsafe. My suggestion is to disable the *unsafe* permissions by default, which helps make flatpaks actually sandboxed by default and still allows for a usable system in my experience.

I think I agree that pushing for less permissions upstream is more important in the short and medium term. After all, it's probably more likely that unsafe permissions will cause harm when legit apps are exploited than an app being malicious in the first place. The latter is the threat model my suggestion is more concerned with.

I'm pretty busy with school but organizing those efforts seems like a neat idea. For example, [Okular](https://flathub.org/apps/org.kde.okular) (verified) gives itself the `x11` permission, despite also giving itself the safe `fallback-x11` permission, which should be all it needs. It also gives itself the `home` filesystem, and I haven't found what breaks when revoking it because it fully supports portals.

**Comment by RoyalOughtness** [comment]
@starkle an example of how easy it can be to get upstream changed :smile: https://github.com/flathub/io.github.celluloid_player.Celluloid/issues/98#issuecomment-1866183009

**Comment by boredsquirrel** [comment]
Celluloid is great. Btw I started a project of [recommended Flatpak Apps](https://github.com/trytomakeyouprivate/Recommended-Flatpak-Apps/) following best practices. It may have some errors and for sure missing applications (like Fractal, which is great!)
