### ISSUE TITLE
replace openssl with libressl

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#136]
I am not sure how recent the big criticism of openssl was, but libressl is not in fedora.

https://copr.fedorainfracloud.org/coprs/murzen/murzenusrepo/package/libressl/

that copr seems to be well made, even though the last version is very old. Using that spec file could be useful for replacing openssl.

https://copr-dist-git.fedorainfracloud.org/cgit/murzen/murzenusrepo/libressl.git/tree/libressl.spec

**Comment by RoyalOughtness** [comment]
The underlying motivations for libressl existing at all no longer exist. The issue is archaic and the only distros that ever made an effort to support it have switched back to openssl years ago (and for good reason):

https://alpinelinux.org/posts/Alpine-3.9.0-released.html
https://wiki.gentoo.org/wiki/LibreSSL

also see: https://lwn.net/Articles/841664/
