### ISSUE TITLE
re-evaluate priority of easy security switches and settings

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#139]
I want to comment on the last PR that was closed.

For one, I am really unhappy with the discussion culture here. Issues and comments are blocked without a possibility to explain ideas.

Every line of code that is not "hardening" is rejected, even if it improves the user-friendliness a lot.

No, having secure presets by default and a single opt-out is not enough. And no, `systemctl` with three different commands (if you miss one, it does not work) is not user friendly. That is the sole purpose of `just`, to make things easy.

This distro will never become "batteries included" like I imagine the ublue projects idea. It may be a good base, but without any things making changes easy, this is not a good enduser experience.

Secureblue, just like ChromeOS, could be a perfect "kids laptop" distro, that can be deployed everywhere, autoupdates, is secure by default and can be easily set up by an admin. But not if its incomplete as there is no easy tooling for common steps.

We could make a wiki explaining all the steps, but really a single, never-changing set of commands is how it should be done.

If we do changes, there has to be a way to reset them for **temporary** softening of the security, and then to set them again. If these changes are not documented and easy to understand, apply oneself, revert etc, that is bad UX.

But to be honest, I dont feel like contributing my time anymore to this project, which is sad as I think it is a great one. But not in this atmosphere, I am sorry.

**Comment by RoyalOughtness** [comment]
The discussion culture is fine. Discussions about new functionality and changes that are in-scope are ongoing and healthy, and other participants in the project have been warned **zero** times. This is not a project issue, it's specific to your behavior. You have been issued official warnings for code of conduct violations many times. I have been incredibly lenient in not banning you from the project. 

Your repeated attempts to modify the scope of the project are not up for discussion and you have been warned about this multiple times. Improving systemd's user experience is in no way in scope of this project. 

You continue to focus on your own personal priorities regardless of whether they're in scope for the project. This is inappropriate and unprofessional especially given that this is after several formal warnings. Please reevaluate your behavior before continuing to engage with this project or any other open source project for that matter. 

I have been lenient with respect to the code of conduct so far, which permits a ban after 1 warning. Given you have accumulated several, if you continue to fail to respond to constructive feedback and/or focus on what's best for your goals instead of the project goals and scope, you will be issued a 72 hour ban.
