### ISSUE TITLE
Enable Hibernate

### ISSUE THREAD

**Issue by arRco4y7** [secureblue/secureblue#148]
Is it possible to enable the hibernate functionality in the image?

**Comment by RoyalOughtness** [comment]
@arRco4y7 I'm not opposed to it on the surface and I didn't realize it was disabled. What does it entail to enable it?

**Comment by arRco4y7** [comment]
I'm not sure but according to the fedora magazine post there is an issue with kernel lockdown mode:
> 2022-12-11 UPDATE: There is a new rather severe caveat to this article. If Secure Boot is enabled and the kernel boots in lockdown mode, hibernation does not work as long as the kernel does not support signed hibernation images.
https://fedoramagazine.org/hibernation-in-fedora-36-workstation/

**Comment by RoyalOughtness** [comment]
Looks like it is sadly not yet possible with lockdown: https://gist.github.com/eloylp/b0d64d3c947dbfb23d13864e0c051c67?permalink_comment_id=4405623#gistcomment-4405623

And lockdown won't be modified since it provides significant security advantages.

If signed hibernation images become supported by the kernel, please reopen this ticket.
