### ISSUE TITLE
harden bashrc, applications and user PATH

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#150]
https://madaidans-insecurities.github.io/linux.html#examples

The problem is pretty basic:

### Paths
```
user@PC:~$ echo $PATH
/var/home/user/.local/bin:/var/home/user/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
```

These are the default BASH PATHs. only `/var/home/user/.local/bin` and `/var/home/user/bin` are relevant here.

changing the ownership to them to root, and making them read-only and executable will mean everything works normally, but only with sudo edits work.

```
pkexec chown root $HOME/bin && pkexec chmod -R 755 $HOME/bin
pkexec chown root $HOME/.local/bin && pkexec chmod -R 755 $HOME/.local/bin
```
 
### Application directory
next problem: the `Exec=` arguments in the `$HOME/.local/share/applications/` desktop entries.

I am not sure if this would break especially Flatpak installation, and I assume so. But hardening the directory the same would be needed to make it secure actually.

### Shell config
As Bash is the only one preinstalled, the same hardening needs to be applied to `$HOME/.bashrc`.

As the default bashrc does not read any other directories or files, this may be enough.

I would appreciate adding the same hardening for fish and zsh, but if this is done in Yafti this would make little sense, as on first run those are probably not installed. If a user layered them before rebasing to secureblue, then it would make sense.

---

If there is something missing please add. But I think this should be enough?

Developer things are not preinstalled, so `go`, `cargo`, `npm`, etc are all not necessary.

Maybe something for `pip`, but the executables are also in `$HOME/.local/bin`. (pip is the best way to install isolated python tools like `pyclip` needed for Waydroid)

**Comment by RoyalOughtness** [comment]
This is a real problem (actually a set of problems) but the solutions are not so simple. 

Setting bin paths to root accomplishes nothing since $PATH is writable by the user. So a compromised user account doesn't need to modify binaries, it can just drop malicious binaries in a different directory and overwrite $PATH.

On top of that, please read the first part of the "The Nonexistent Boundary of Root" section in the Madaidan article you linked again. A compromised non-root user account can be considered equal to root due to the number of attack vectors available to retrieve the sudo password. With this in mind, changing the ownership of files from a wheel user to root accomplishes functionally nothing. 

 Please see the kicksecure documentation for more details on the problems here and potential solutions:

https://www.kicksecure.com/wiki/Dev/Strong_Linux_User_Account_Isolation#LD_PRELOAD
https://www.kicksecure.com/wiki/Root#Prevent_Malware_from_Sniffing_the_Root_Password

From the docs: "Mounting all user-writeable places such as /home and /tmp as non-executable is not a solution because an attacker can use the bash interpreter to bypass the restrictions using bash /path/to/script."

A key piece of the solution here is to use an isolated, non-wheel user account for non-admin actions, and then have a dedicated admin account. This is ultimately a user decision and not something secureblue can do for the user.

That said, there may be components of partial solutions in there that we're missing.

**Comment by boredsquirrel** [comment]
agree that any process can just invoke bash to execute whatever script.

I am not sure what you mean with $PATH is writable, as it would be chown root and not writable in that case? Is that not possible?

It seems like a security improvement, even though not a complete one of course. So I would say

1. Improve the wheel users security using such measurements
2. include the creation of an unprivileged user account in Yafti and check issues there.

I will open anotheri issue in 2. as I tried it and there are some problems / requirements that need to be fulfilled to do that.

**Comment by RoyalOughtness** [comment]
> $PATH is writable

It's writable. you can just export it in the running session.

> Improve the wheel users security using such measurements

Using what measurements?

> include the creation of an unprivileged user account in Yafti and check issues there.
This is not something that belongs in yafti or just. At best we could add a post-install instructions.md or something.

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/dd7135761ae02fbb744c771e391190ada39dd48e

**Comment by boredsquirrel** [comment]
this is an okay stage for now.

I am in discussion about SELinux confined users. Basically you have 2 permission systems, the unix groups and SELinux contexts.

Because currently it is somewhat problematic to have the "regular user" without wheel access. How do you want to secure your path, shell config, ssh keys, gnupg keys?

Normally you could chown root them and make them only readable. Using SElinux a similar thing can then be used in the future. So currently this is somewhat problematic

**Comment by RoyalOughtness** [comment]
@trytomakeyouprivate the goal of keeping your regular user wheelless is to make it so that a compromised bashrc is less impactful. Since you're not entering your sudo password on a wheelless account, there isn't a sudo password that can get stolen by a fake bash alias to sudo.

However you're right that it's not ideal in a lot of ways. SELinux confined users is the way forward.
