### ISSUE TITLE
PAM hardening

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#17]

**Comment by boredsquirrel** [comment]
https://github.com/pyllyukko/harden.yml @pyllyukko
https://www.linux.com/news/hardening-pam-framework/
https://github.com/trimstray/the-practical-linux-hardening-guide/wiki/PAM-Module @trimstray

**Comment by RoyalOughtness** [comment]
@34N0 I assigned this to you as you expressed interest previously. If you're not working on this, let me know and I'll unassign you.

**Comment by wandapeter** [comment]
I am currently working on this.

**Comment by wandapeter** [comment]
So Kicksecure's account locking works the following:

It locks the account forever after 50 failed tries in 15 minutes.
That means that theoretically a brute force attack could try a password every 18 seconds.

We could just copy this since it seems reasonable.

One thing for the long term, i feel like since locking out users is dangerous without a root account or central admin i'd like to work on a PAM module which ramps up entry delays like it's implemented in GOS but for now, we can stick with a config like the one in kicksecure.

**Comment by RoyalOughtness** [comment]
> So Kicksecure's account locking works the following:
> 
> It locks the account forever after 50 failed tries in 15 minutes. That means that theoretically a brute force attack could try a password every 18 seconds.
> 
> We could just copy this since it seems reasonable.

Makes sense, please go ahead with that

**Comment by boredsquirrel** [comment]
Another brute force prevention is probably not possible? Sounds good, but "lock forever" could also be used negatively.

**Comment by RoyalOughtness** [comment]
> Another brute force prevention is probably not possible? Sounds good, but "lock forever" could also be used negatively.

That's a good point. Maybe a 24 hour lock or something like that @34N0? or 72? I'm indifferent to the exact value but I agree that forever is probably overkill.

**Comment by boredsquirrel** [comment]
afaik really secure cooldown bruteforce prevention is only possible with a secure element. This would increase the hardware requirements.

1h sounds enough tbh, but threat model is a big question here. Do you want your machine to be uncrackable when you will never have access to it again?

**Comment by RoyalOughtness** [comment]
> afaik really secure cooldown bruteforce prevention is only possible with a secure element. This would increase the hardware requirements.

I have no idea what "secure element" means, but that aside this task is about improving on the defaults not perfection. [Perfect is the enemy of good.](https://en.wikipedia.org/wiki/Perfect_is_the_enemy_of_good)

**Comment by boredsquirrel** [comment]
agree, this is the reason why GrapheneOS is only on Pixels, even though other phones could use its benefits too

https://en.wikipedia.org/wiki/Secure_element

**Comment by RoyalOughtness** [comment]
> agree, this is the reason why GrapheneOS is only on Pixels, even though other phones could use its benefits too
> 
> https://en.wikipedia.org/wiki/Secure_element

sure, but we won't be scoping this project down to one brand and model of hardware as that would be incredibly restrictive.

**Comment by wandapeter** [comment]
:+1:  Yeah I thought about that too. Let's just say 24 hours. This is surely enough and shouldn't bother users since they have 50 tries!

@trytomakeyouprivate I don't think you know what role the TPM secure element plays in a system. The chip is used to store cryptographic keys. In case of user authentication the TPM plays a much greater role in android since android is FBE (file based encrypted) and not FDE (full disk encrypted).

Linux encryption is generally not the most modern and best approach and there are pushes to change how encryption is handled. For instance there are ways to use PAM and TPM together with FSE (File System Encryption) to lock the users `/home` or use systemd to lock `/var /etc /home` on logout which would solve some issues.

There's this famous post explaining the issues. We might someday try this on secureblue but for now this is very complicated: https://0pointer.net/blog/authenticated-boot-and-disk-encryption-on-linux.html

As for GOS, TPMs are much more widespread in the Notebook/Desktop world, since Windows made it a requirement a few versions ago. This is different in the mobile world. Pixel phones have a very strong TPM but the reasons why GOS uses them are mostly others, like hardware security patches and the ability to relock the bootloader.

That means that in our current encryption implementation, PAM does not really protect data, but permissions. OFC if criminals or the state take your device running but logged out, some PAM brute-force protection is required. But then there are other hardware based protection measures important which aren't in scope. It's just a flaw of FDE.

But the PAM brute-force protections are also needed in other scenarios. Especially local privesc, where for instance an attacker having the privileges of some process (i.e. being `www-data`) brute-forces your user password. Or `sudo` is brute forced for further privesc...

Longer comment but i hope you get my points :smile:. I feel like it can be dangerous to quote GOS in this project in every issue since android is another OS implementing a lot of things differently!

Also: I just want to write a PAM module because it's fun haha :smile:

**Comment by wandapeter** [comment]
I've made a mistake! PAM is configured using the `authselect` utility.

I thought the default configuration profile is created on first boot but that is not the case.
If we change the configuration directly the use of `authselect` will overwrite our configuration. 

So we either:

- Overwrite the default configuration profile of `authselect` in a way in which it does not get overwritten again if `authselect` gets updated
- Remove `authselect`

Thoughts?

**Comment by wandapeter** [comment]
Or maybe we create a custom `authselect` profile and then add a script which selects this profile on build

**Comment by RoyalOughtness** [comment]
> I thought the default configuration profile is created on first boot but that is not the case.

If it doesn't get created on first boot, isn't that better? Since we want to create it ourselves?

> If we change the configuration directly the use of authselect will overwrite our configuration.

So if the user doesn't use authselect, it's fine?

> Overwrite the default configuration profile of authselect in a way in which it does not get overwritten again if authselect gets updated

Why would updating authselect overwrite our config?

Can you please clarify what you are saying above?

**Comment by wandapeter** [comment]
> If it doesn't get created on first boot, isn't that better? Since we want to create it ourselves?

It is what made me think the default profile is the one which is there on first boot. Which would be ours since we replace it in the build.

> Why would updating authselect overwrite our config?

There are default profiles located in `/usr/share/authselect` and `/usr/share/authselect/vendor`  Those profiles seem to get added and modified in the `.spec` file. `authselect` will override the files in `/etc/pam.d` with the files in those profiles.

> So if the user doesn't use authselect, it's fine?

Yes since `authselect` is an indipendet configuration cli and not part of PA
I think the best solution is to createM.

I am leaning towards creating  our own profile and keep `authselect`.  If i do that we could also use that to define what login methods we want like:

- I.E. do we allow logging in with fingerprints as a single factor?
- Should we add yubikey authentication as an optioanal feature?
- Do we allow any network authentication services or only local users?

**Comment by RoyalOughtness** [comment]
That sounds fine, I'll let you decide
