### ISSUE TITLE
docs: Secureblue hardening sources Document

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#176]
I think it would be nice to have a `SOURCES.md` document or something, where we can add sources for various hardening measurements.

This could just be an alphabetically ordered list, or grouped by categories (which I think would be better)

- https://github.com/secureblue/secureblue/issues/173#issuecomment-1909340134
- https://github.com/secureblue/secureblue/issues/161#issuecomment-1902740961
- https://github.com/secureblue/secureblue/issues/161#issuecomment-1902874679
- ...

**Comment by RoyalOughtness** [comment]
We do need additional documentation, but it would be much more useful inline. Examples:

https://github.com/secureblue/secureblue/blob/live/config/files/usr/etc/sysctl.d/hardening.conf#L47

https://github.com/secureblue/secureblue/blob/live/config/files/usr/etc/chromium/policies/managed/hardening.json.readme.md?#L1

I'll close this but only because we need more issues/PRs that are specific so we can keep track of what places need better documentation (the sysctl changes come to mind).

Please open new issues for specific inline documentation gaps, or even better, PRs :smile:
