### ISSUE TITLE
[UX] Avoid Using `rpm-ostree` In First Setup Experience

### ISSUE THREAD

**Issue by czhang03** [secureblue/secureblue#196]
In the first setup experience, there were several commands to set kargs: https://github.com/secureblue/secureblue/blob/live/config/files/usr/share/ublue-os/firstboot/yafti.yml . However, these commands almost always fail without any indication to the user, as the `rpm-ostree` are typically busy during the first setup experience, hence will cancel all the `rpm-ostree` command, including kargs hardening.

As there is currently no way to queue commands using `rpm-ostree` (https://github.com/coreos/rpm-ostree/issues/2969), I think the best way is to let the user run the command manually. 

Maybe we can have a button linked in yafti to the [POSTINSTALL-README.md](https://github.com/secureblue/secureblue/blob/live/POSTINSTALL-README.md), and add the documentations in there.

**Comment by xynydev** [comment]
https://github.com/ublue-os/bling/issues/101 might be of interest

**Comment by boredsquirrel** [comment]
The command is the one for the kargs.

#169 is important here, as the kargs have to exclude the one that broke boot for me, it is then experimental and has to be applied manually.

I think good UX would be:
- welcome dialog
- OS infos
- apply minor things
- "Increase the systems security. This will take a while and automatically restart your Computer" `rpm-ostree cancel && apply kargs && reboot` 

I think Yafti is not the best UX, because its lack of any progress indicator is really "Windows like" ("we are setting up your System, just wait a while...").

Spawning a terminal running the command could be done, but there is no universal one for all Desktops like XTerm.

https://github.com/ublue-os/yafti/issues/194

**Comment by RoyalOughtness** [comment]
> #169 is important here

It's not relevant here since it's been separated out into a separate command that isn't invoked by yafti.


> 
> I think good UX would be:
> 
> * welcome dialog
> * OS infos
> * apply minor things

You are suggesting a UX that already exists.


> * "Increase the systems security. This will take a while and automatically restart your Computer" `rpm-ostree cancel && apply kargs && reboot`

This doesn't work because `rpm-ostree cancel` doesn't guarantee that all queued rpm-ostree tasks will be cleared out. What @xynydev mentioned is the way forward, once it's upstream.

> I think Yafti is not the best UX, because its lack of any progress indicator is really "Windows like" ("we are setting up your System, just wait a while...").

You should open an issue against yafti, not secureblue. https://github.com/ublue-os/yafti



> Spawning a terminal running the command could be done, but there is no universal one for all Desktops like XTerm.
> 
> [ublue-os/yafti#194](https://github.com/ublue-os/yafti/issues/194)

It's not at all clear what problem you are trying to solve with this suggestion.

**Comment by RoyalOughtness** [comment]
Stop gap fix for this pushed here: https://github.com/secureblue/secureblue/commit/05723949f91b736a3709f80e61b18f7d359403b3

This unbreaks the experience for now. Once the initramfs module is available and stable, we will use it to automate this process.

**Comment by boredsquirrel** [comment]
> You are suggesting a UX that already exists.

The stress was at a quick intro and not waiting for the long rpm-ostree command to finish. To turning around the order and ending it with an automatic reboot.

> This doesn't work because rpm-ostree cancel doesn't guarantee that all queued rpm-ostree tasks will be cleared out. 

Oh that is strange. Is there no way to do this then?

Yes, a progress indicator support is probably a core yafti feature.

> It's not at all clear what problem you are trying to solve with this suggestion.

A terminal output makes it very easy to display the native output of an invoked process. To not hide away anything important

**Comment by RoyalOughtness** [comment]
> A terminal output makes it very easy to display the native output of an invoked process. To not hide away anything important

yafti already has this functionality

**Comment by fiftydinar** [comment]
I would want to reopen this issue, since rebuilding initramfs inside the image is possible & very easy now with this script:

```
#!/usr/bin/env bash

set -euo pipefail

rpm-ostree cliwrap install-to-root /
QUALIFIED_KERNEL="$(rpm -qa | grep -P 'kernel-(\d+\.\d+\.\d+)' | sed -E 's/kernel-//')"
/usr/libexec/rpm-ostree/wrapped/dracut --no-hostonly --kver "${QUALIFIED_KERNEL}" --reproducible -v --add ostree -f "/lib/modules/${QUALIFIED_KERNEL}/initramfs.img"
chmod 0600 "/lib/modules/${QUALIFIED_KERNEL}/initramfs.img"
```

This would assure that modprobe changes will be applied.
