### ISSUE TITLE
TLP sometimes loses pendrives

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#201]
Using kinoite-laptop-userns-hardened

This is a known and old TLP bug.

I am not sure if TLP is the best tool for all hardware either. 

On my laptop sometimes pendrives dont show up. `sudo tlp false` fixes this by manually switching to AC mode.

Some time ago I went and made my own `tlp.conf` but I lost it.

I could try to find the fitting setting and add a minimal conf file to /etc so users can still change it if the want to. 

linrunner.de/tlp/settings/

[Ostechnix article](https://ostechnix.com/how-to-optimize-laptop-battery-life-with-tlp-in-linux/)

It should be

```
USB_AUTOSUSPEND=0
```

There is an option to blocklist devices from autosuspend too, which may be useful for usb ports.

We should watch out for Framework as those are full of usb ports, which are known to cause battery drain, but disabling autosuspend could have especially negative consequences.

**Comment by RoyalOughtness** [comment]
This is upstream in multiple ways.

**Comment by boredsquirrel** [comment]
lol but if TLP is included it should at least be easy to avoid this common issue. Documentation?

**Comment by RoyalOughtness** [comment]
`tlp`'s installation and corresponding config is owned by ublue bling. 

> Documentation?

It is not in secureblue nor ublue's scope to document upstream issues.

**Comment by boredsquirrel** [comment]
Okay thanks I will ask ublue then. For me as soon as you package software you can be held accountable for it. I suppose upstream will not fix this in a looong time and this config is an easy, even though not "real" fix

**Comment by RoyalOughtness** [comment]
>  For me as soon as you package software you can be held accountable for it.

neither ublue nor secureblue is packaging tlp.

**Comment by boredsquirrel** [comment]
I would call "preinstalling on an immutable distro" packaging tbh.

Reported upstream

**Comment by RoyalOughtness** [comment]
> I would call "preinstalling on an immutable distro" packaging tbh.

You would be incorrect. There is no concept of packaging in the industry that would refer to it in such a way. And even if there was, aside from distro-specific issues, package maintainers are **not** responsible for bugs in the software they're packaging. Do not bother fedora package maintainers with out of scope requests. Evaluate where the issue belongs carefully and only then open a report.

This is yet another example of your prioritization of your own interests over community goals and norms. You have consistently declined to follow basic concepts of ownership and scope, even after a 3 day ban. You have repeatedly opened obviously out of scope issues here and who knows where else. In doing so you have demonstrated a disregard for other people's time and effort. My time is better spent on other things instead of constantly reminding you of these basics and the code of conduct.

If you value access to this community at all, cut it out.
