### ISSUE TITLE
[BUG] Unable to login on LightDM

### ISSUE THREAD

**Issue by wandapeter** [secureblue/secureblue#228]
**Describe the bug**
This was found while testing for https://github.com/34N0/pam-authramp/issues/67. Currently user authentication fails completely with LightDM.

**To Reproduce**

1. rebase to cinnamon-main-hardened
2. try to login

**Expected behavior**

user authenticates successfully

**Actual behavior**

- LightDM states "failed to start session"

According to the contents of `/var/log/lightdm/lightdm.log` the issue seems to be configuration based: "Failed to find session configuration default".

**Comment by RoyalOughtness** [comment]
is this on staging or latest?

**Comment by wandapeter** [comment]
> is this on staging or latest?

both

**Comment by RoyalOughtness** [comment]
Unable to repro. Rebased to `ostree-image-signed:docker://ghcr.io/secureblue/cinnamon-main-hardened:latest` and login succeeded.

**Comment by RoyalOughtness** [comment]
do you have any local overrides?

**Comment by wandapeter** [comment]
all my tests are done on a rebase from a fresh silverblue snapshot. excuse the screenshot:
![status](https://github.com/secureblue/secureblue/assets/92182849/3cfdb4a9-db7f-4dab-85bd-c48cab3a1bbe)

**Comment by RoyalOughtness** [comment]
Very strange. Let me try a VM later

**Comment by RoyalOughtness** [comment]
some more details to confirm I have no local overrides:

```
$ diff /usr/etc/security/pwquality.conf /etc/security/pwquality.conf -s
Files /usr/etc/security/pwquality.conf and /etc/security/pwquality.conf are identical
```

```
$ diff /usr/etc/security/faillock.conf /etc/security/faillock.conf -s
Files /usr/etc/security/faillock.conf and /etc/security/faillock.conf are identical
```

**Comment by RoyalOughtness** [comment]
also:

```
$ diff /usr/etc/login.defs /etc/login.defs -s
Files /usr/etc/login.defs and /etc/login.defs are identical
```

**Comment by wandapeter** [comment]
Since this is only an issue on my side, i'm guessing the issue lies with my testing VM. I am closing this.

**Comment by boredsquirrel** [comment]
strange, I have the same issue. `virt-manager qemu qemu-kvm` on `kinoite-main-userns-hardened`.

Fedora Sericea image installed without LUKS password and with a user account, no root account.

After finished installation, before logging in through the display manager I exited to TTY, rebased to unsigned `cinnamon-main-userns-hardened` and then tried to rebase to signed in TTY, but it failed due to no DNS (I think), graphical login gave the same error message.

so not the signed image yet, and no kargs set yet. I can try in physical media but it seems this is reproducible.
