### ISSUE TITLE
[FEAT] Chat on Matrix instead of Discord

### ISSUE THREAD

**Issue by boredsquirrel** [secureblue/secureblue#230]
**Describe the benefit this feature would provide to the project**
Matrix is not controlled by a centralized authority, not proprietary, supports encryption, is a free standard, has native clients in Qt and GTK (no electron)

**Describe the solution you'd like**
A matrix space to discuss secureblue, maybe with rooms for additional things

**Describe alternatives you've considered**
Creating issues for everything which is often a pretty bad solution

**Declaration**
- [x] I declare that I have read the README and my feature request is in-scope.

**Comment by RoyalOughtness** [comment]
Discord has significantly more moderation security features. If you don't want to use it, that's your prerogative.

**Comment by boredsquirrel** [comment]
I would be happy to discuss this further. Matrix does have a lot of administration tools.

You can create a public space with public and secret rooms. Rooms or spaces may require invitation, and may or may not be E2EE. You can give people very fine grained admin/management permissions for every need. You can list rooms publically or keep them hidden.

Also I would be happy to keep such issues open longer. There is no discussion feature or anything, issues are the only accessible media to discuss, and as Github hides closed issues, closing them makes them way less visible.

**Comment by RoyalOughtness** [comment]
We will only be using Discord. Please stop bumping or opening issues unless they pertain to the actual images. I close issues when no action will be taken or when the issue is complete. 

Please stop with your continued pattern of entitled behavior. You are not entitled to dictate whether things are open for discussion, on this or any project. You have been temporarily banned for this before and if you continue you will be permanently banned. This is your last warning of dozens. I have better things to do.

**Comment by boredsquirrel** [comment]
I did not dictate anything, I asked a question that I think is relevant ([I am not the only one thinking this](https://drewdevault.com/2021/12/28/Dont-use-Discord-for-FOSS.html)) and all I asked was to keep this issue open until multiple people could say what they think about it. Also your argumentation was the lack of moderation features, which is not true.

Please stop accusing me of things that are not true.

**Comment by RoyalOughtness** [comment]
@trytomakeyouprivate 

> multiple people could say what they think about it.

This implies you want it to remain open for discussion. It isn't, and you are not entitled to dictate that it be.

You have been banned for one week. Please reconsider your behavior thoroughly as I have been incredibly lenient till this point and no longer have time to be.

**Comment by boredsquirrel** [comment]
I have no idea how you can think this is normal behavior. You seem to have some serious control issues. I am sorry but this is not how you treat people.

**Comment by RoyalOughtness** [comment]
@trytomakeyouprivate 

I have been nothing but lenient. You are making me regret my leniency, as I let you break the code of conduct dozens and dozens of times without a ban.

Now after all of that, you come back playing the victim as a crybully. If this was really a matter of me being controlling, there would be other users in the same boat, yet I haven't given anyone so much as a warning.

You need to learn how to abide by a community's code of conduct. Just because a project is open source, doesn't mean you get to decide what's in and out of scope. This project has a clear scope declaration and CoC that you've repeatedly shown a disregard for.

You are permanently banned due to your continuous disregard for the project's scope and code of conduct, and with no indication of an intent to bring your behavior in line with the code of conduct.
