### ISSUE TITLE
[BUG] Network Won't Connect When The Time Is Not Correct

### ISSUE THREAD

**Issue by czhang03** [secureblue/secureblue#268]
**Describe the bug**
The network will not connect when the time is not correct. HTTPS protocol requires the local time to be correct in order to make the connection. 
However, when the time is not correct, NTS also won't run in this case. The failure to run NTS is probably caused by the fact that all the NTS sever is listed as url, and DNS is set to resolve over TLS, which seems to be disrupted by the incorrect system time.  I suspect using an IP address of the time sync server as a fallback might fix this problem.
Connection to an IP address over HTTP works fine when the time is off, again suggesting it is a problem with TLS and DNS resolution.

Besides this, I also noticed that `systemd-timedated` and `chrony` are active on the system. AFAIK, they serve similar purpose, is there a reason to leave both of them active? 

**UPDATE**: both `systemd-timedated` and `chrony`  are active on ublue `sliverblue-main` base image.

**To Reproduce**
1. Change system time to 2 months from now.
2. Turn on automatic time sync.
3. Go to any webpage (even HTTP one), and it will not connect. The problem occurs in the DNS resolution phase. 

**Expected behavior**
The time will be correctly synced, and the network will connect.

**Actual behavior**
The time did not sync (remains the incorrect time), and the network will not connect. 

**Your current image**
```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 2min 6s ago
Deployments:
  ostree-image-signed:docker://ghcr.io/secureblue/silverblue-main-hardened:latest
                   Digest: sha256:eaec86073e5ced4cf2b4ea1734911aeab64a1d22812b63acfc97b40734761e32
                  Version: 40.20240428.0 (2024-04-28T18:38:24Z)
                     Diff: 3 upgraded, 1 removed
          LayeredPackages: fish ibus-table-mathwriter

● ostree-image-signed:docker://ghcr.io/secureblue/silverblue-main-hardened:latest
                   Digest: sha256:d8842b00a03ce9e968c0ac8e8fe1bec5e01bc44cb9c58ac8995938a8544ba7a4
                  Version: 40.20240427.0 (2024-04-27T18:37:53Z)
          LayeredPackages: fish ibus-table-mathwriter

  ostree-image-signed:docker://ghcr.io/ublue-os/silverblue-main:latest
                   Digest: sha256:63e552a623f4e175f3ab161df97ec80fec409bcdbe1c7f1fab34464780713552
                  Version: 40.20240428.0 (2024-04-28T07:16:48Z)
          LayeredPackages: fish ibus-table-mathwriter
```

**This issue is not reproducible on ublue `silverblue-main` image**

**Comment by RoyalOughtness** [comment]
Thanks, I will look into this

**Comment by czhang03** [comment]
I have done some experiment, and can confirm that a couple fallback using IP addresses indeed works.

Here I try to set my time to an incorrect time:
```
> chronyd -Q -t 3 'server ntp1.time.nl iburst maxsamples 1'
2024-02-29T16:35:34Z chronyd version 4.5 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP +SCFILTER +SIGND +ASYNCDNS +NTS +SECHASH +IPV6 +DEBUG)
2024-02-29T16:35:34Z Disabled control of system clock
2024-02-29T16:35:37Z Timeout reached
2024-02-29T16:35:37Z chronyd exiting

> chronyd -Q -t 3 'server 94.198.159.10 iburst maxsamples 1'
2024-02-29T16:35:53Z chronyd version 4.5 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP +SCFILTER +SIGND +ASYNCDNS +NTS +SECHASH +IPV6 +DEBUG)
2024-02-29T16:35:53Z Disabled control of system clock
2024-02-29T16:35:53Z System clock wrong by 5180404.268605 seconds (ignored)
2024-02-29T16:35:53Z chronyd exiting
```

where `94.198.159.10` is the ip address of `ntp1.time.nl`: https://www.ntppool.org/a/TimeNL. 

However, I don't know if NTS supports IP addresses, since I was not able to find a server supporting NTS that provides IP: https://github.com/jauderho/nts-servers

**Comment by czhang03** [comment]
More experiments: 

1. When NTS is enabled, time query to IPs will always time out:
```
chronyd -Q -t 3 'server 129.6.15.28 iburst nts maxsamples 1'
2024-02-29T16:57:30Z chronyd version 4.5 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP +SCFILTER +SIGND +ASYNCDNS +NTS +SECHASH +IPV6 +DEBUG)
2024-02-29T16:57:30Z Disabled control of system clock
2024-02-29T16:57:33Z Timeout reached
2024-02-29T16:57:33Z chronyd exiting

> chronyd -Q -t 3 "server 94.198.159.10 iburst nts maxsamples 1"
2024-02-29T16:58:04Z chronyd version 4.5 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP +SCFILTER +SIGND +ASYNCDNS +NTS +SECHASH +IPV6 +DEBUG)
2024-02-29T16:58:04Z Disabled control of system clock
2024-02-29T16:58:07Z Timeout reached
2024-02-29T16:58:07Z chronyd exiting
```

2. I have also tried to edit my `chrony.conf` file to:
```
# https://github.com/GrapheneOS/infrastructure/blob/main/chrony.conf
server time.cloudflare.com iburst nts
server ntppool1.time.nl iburst nts
server nts.netnod.se iburst nts
server ptbtime1.ptb.de iburst nts

# **CHANGES:** use IP (without nts) as fallback
server 94.198.159.10 iburst
server 129.6.15.28 iburst

minsources 2
authselectmode require

# EF
dscp 46

driftfile /var/lib/chrony/drift
ntsdumpdir /var/lib/chrony

leapsectz right/UTC
makestep 1.0 3

rtconutc
rtcsync

cmdport 0
```
Then I restarted `chrony.d`, set automatic date time. Yet, there is still no connection, nor will the system time sync with these servers. Even though both of these servers are reachable via command `chronyd -Q -t 3 'server <ip-address> iburst maxsamples 1'`.

---
* The `94.198.159.10` is the ip address of `ntp1.time.nl`: https://www.ntppool.org/a/TimeNL ; and `129.6.15.28` is the ip address of `time-a-g.nist.gov`: https://tf.nist.gov/tf-cgi/servers.cgi

**Comment by czhang03** [comment]
Here are some related articles and issues, prehaps their solution can be of inspiration:
- https://cyounkins.medium.com/encrypted-dns-ntp-deadlock-9e378940b79f
- https://github.com/openwrt/openwrt/issues/9408
- https://news.ycombinator.com/item?id=34177331

**Comment by ghost** [comment]
If my memory is right raspberry pi (due to no memory when unplug) had a similar issue, they had found a workaround to allow ntp to run 1 time in insecure mode at boot, and after running normally. (wort checking here it's more secure than allowing a insecure fallback every time)

**Comment by czhang03** [comment]
I have confirmed that the command `sudo chronyd -q -t 3 'server 94.198.159.10 iburst maxsamples 1'` would reset system time when the system time is incorrect. But this would need to fire before `chronyd.service` get loaded. I don't know what would be the correct way to do this.

And obviously, ideally we would only do this as a fallback, that is we will still connect via NTS, if possible, even as a one shot time sync.

**Comment by czhang03** [comment]
I see a problem with the one-shot method @BirdInFire suggested. Unlike a pi, a laptop will sometimes boot in an environment without internet (coffee shop etc.). Then the one shot wouldn't work. I think maybe adding a fallback is the easiest and most reliable way to resolve this. 

And adding fallback without NTS poses minimal security risk (assuming we don't want the user to deal with this problem), since it is only a fallback when most of the secure method failed, that would indicate that the user is unlikely to have internet. 

Alternatively, another idea is to disable DoT specifically for chrony when internet is unreachable. But I don't know if this approach is technically possible.

**Comment by ghost** [comment]
> I see a problem with the one-shot method @BirdInFire suggested. Unlike a pi, a laptop will sometimes boot in an environment without internet (coffee shop etc.). Then the one shot wouldn't work. I think maybe adding a fallback is the easiest and most reliable way to resolve this.
> 
> And adding fallback without NTS poses minimal security risk (assuming we don't want the user to deal with this problem), since it is only a fallback when most of the secure method failed, that would indicate that the user is unlikely to have internet.
> 
> Alternatively, another idea is to disable DoT specifically for chrony when internet is unreachable. But I don't know if this approach is technically possible.

Disabling DoT may fix DNS but not NTS and not HTTPS / TLS so I would be complicated for not fixing the issue totally.

I also maintain that a fallback is (in my mind) too risky to be a default (maybe a yafti setting in the first boot ?) or a manual command (like for the unsafe kernel arguments) ?

**Comment by RoyalOughtness** [comment]
> UPDATE: both systemd-timedated and chrony are active on ublue sliverblue-main base image.

@czhang03 I think you are confusing systemd-timedated and systemd-timesyncd. chronyd on Fedora replaces timesyncd, timedated serves a different purpose

> However, when the time is not correct, NTS also won't run in this case. The failure to run NTS is probably caused by the fact that all the NTS sever is listed as url, and DNS is set to resolve over TLS, which seems to be disrupted by the incorrect system time.

Isn't this correct behavior? It seems like if your time becomes significantly desynchronized, the fix is to manually sync it once so nts can work properly, and then it will be fixed.


> Change system time to 2 months from now.
Turn on automatic time sync.
Go to any webpage (even HTTP one), and it will not connect. The problem occurs in the DNS resolution phase.
Expected behavior
The time will be correctly synced, and the network will connect.
Actual behavior
The time did not sync (remains the incorrect time), and the network will not connect.

The actual behavior seems more or less expected here. 

> And adding fallback without NTS poses minimal security risk

What makes this a better solution than just not desyncing your time?

This seems like expected behavior and not an issue per se. I'll reopen if compelling information is presented that this is not the case.

**Comment by ghost** [comment]
> > UPDATE: both systemd-timedated and chrony are active on ublue sliverblue-main base image.
> 
> @czhang03 I think you are confusing systemd-timedated and systemd-timesyncd. chronyd on Fedora replaces timesyncd, timedated serves a different purpose
> 
> > However, when the time is not correct, NTS also won't run in this case. The failure to run NTS is probably caused by the fact that all the NTS sever is listed as url, and DNS is set to resolve over TLS, which seems to be disrupted by the incorrect system time.
> 
> Isn't this correct behavior? It seems like if your time becomes significantly desynchronized, the fix is to manually sync it once so nts can work properly, and then it will be fixed.
> 
> > Change system time to 2 months from now.
> > Turn on automatic time sync.
> > Go to any webpage (even HTTP one), and it will not connect. The problem occurs in the DNS resolution phase.
> > Expected behavior
> > The time will be correctly synced, and the network will connect.
> > Actual behavior
> > The time did not sync (remains the incorrect time), and the network will not connect.
> 
> The actual behavior seems more or less expected here.
> 
> > And adding fallback without NTS poses minimal security risk
> 
> What makes this a better solution than just not desyncing your time?
> 
> This seems like expected behavior and not an issue per se. I'll reopen if compelling information is presented that this is not the case.

More than an expected behaviour it's actually a security protocol added in (I forgot witch version of ntp) that prevent the change of the time if the time changed is superior to X minute (I also forget the default maximum time as this change is quite old now).

The only case where I could see his time desynchronising is using this images in dual boot with windows (windows would override the time by 1 hours if my memory is exact, but I would recommend him to change the settings himself to align linux to how windows manage time (by him I talk about the autor of the issue not securblue project).

The second case would be raspberry pi (who forget time when electricity is lost) but since it use ARM and ublue do not support arm image yet, I also fail to understand the need to desynchronising this much.

**Comment by czhang03** [comment]
Hi, I should probably be more specific. There are several cases I have encountered this bug: 
- When the CMOS got reset, the time will be desynced;
- If the laptop is completely discharged for too long, then the time will become desync.
- I have a laptop using as home console, and of course, I will need to remove the battery as constantly charging it is a fire hazard. Then, if there is a power outage or the power is unplugged, then the time will get desynced, as there is no CMOS battery in this laptop.

I think this problem is particularly problematic as there is no reasonable error message when the desync has happened. Most browser will only return "website unreachable" as the failure happens in the DNS resolution. So unless the user is specifically trained to debug network error, it is very hard to realize the problem. It took me a long time to pinpoint this bug when I first encountered it.

**Comment by ghost** [comment]
> Hi, I should probably be more specific. There are several cases I have encountered this bug:
> 
> * When the CMOS got reset, the time will be desynced;
> * If the laptop is completely discharged for too long, then the time will become desync.
> * I have a laptop using as home console, and of course, I will need to remove the battery as constantly charging it is a fire hazard. Then, if there is a power outage or the power is unplugged, then the time will get desynced, as there is no CMOS battery in this laptop.
> 
> I think this problem is particularly problematic as there is no reasonable error message when the desync has happened. Most browser will only return "website unreachable" as the failure happens in the DNS resolution. So unless the user is specifically trained to debug network error, it is very hard to realize the problem. It took me a long time to pinpoint this bug when I first encountered it.

to be fair there no chance an untrained user would be on secureblue if he (she) don't know the (at least) very basic of linux (and so the tis issue if time is not correct.

I mean if he cannot debug a time issue (quite easy) he (she) will have a nightmare to even run secureblue as myself run on some bug now and then due to the hardened malloc who are incredibly more difficult to debug.

**Comment by nihil-admirari** [comment]
> However, I don't know if NTS supports IP addresses, since I was not able to find a server supporting NTS that provides IP: https://github.com/jauderho/nts-servers

Cloudflare documents the IPs of their time servers: https://developers.cloudflare.com/time-services/ntp/usage/#linux. They just forgot to get an IP-based certificate.

```sh
openssl s_client \
    -tls1_3 \
    -verify 4 \
    -verify_return_error \
    -connect time.cloudflare.com:4460 \
    < /dev/null 2> /dev/null \
| openssl x509 -noout -ext subjectAltName
```

returns

```
X509v3 Subject Alternative Name: 
    DNS:time.cloudflare.com, DNS:www.time.cloudflare.com
```

Compare with Cloudflare's DoH (`security.cloudflare-dns.com:443`):

```
X509v3 Subject Alternative Name: 
    DNS:security.cloudflare-dns.com, DNS:*.security.cloudflare-dns.com, IP Address:1.0.0.2, IP Address:1.1.1.2, IP Address:2606:4700:4700:0:0:0:0:1002, IP Address:2606:4700:4700:0:0:0:0:1112
```

IPs can be hardcoded in `/etc/hosts` (or Unbound's `local-zone`). It won't really fix the problem, since certificates are short-lived and they fail expiration checks on machines with seriously out-of-sync clocks. However, a combination of IP hard-coding and [`nocerttimecheck 1`](https://chrony-project.org/doc/latest/chrony.conf.html#nocerttimecheck) will allow NTS bootstrap using Cloudflare servers.

Ubuntu ships with a special NTS server with a self-signed certificate to handle NTS bootstrap ([`ubuntu-ntp-pools.sources`](https://git.launchpad.net/ubuntu/+source/chrony/tree/debian/ubuntu-ntp-pools.sources), [`ubuntu-nts.conf`](https://git.launchpad.net/ubuntu/+source/chrony/tree/debian/conf.d/ubuntu-nts.conf)):

```
# The bootstrap server is needed by systems without a hardware clock, or a very
# large initial clock offset. The specified certificate set is defined in
# /etc/chrony/conf.d/ubuntu-nts.conf.
pool ntp-bootstrap.ubuntu.com iburst maxsources 1 nts certset 1
```

```
# This CA is needed for the Ubuntu NTS bootstrap servers.  It has a very large
# validity range (decades into the past and future) to allow systems with a
# very large initial clock drift to use NTS.
# If there is already another certificate set using the same index as this one
# here ("1"), then this CA will get added to that set.
ntstrustedcerts 1 /etc/chrony/nts-bootstrap-ubuntu.crt
```

However, IP addresses of `ntp-bootstrap.ubuntu.com` aren't documented anywhere, and [Ubuntu uses its NTP servers to count Ubuntu users](https://lwn.net/Articles/776327/), which means they probably can't be used outside of Ubuntu.

To fix the bootstrap problem, Google has proposed [Roughtime protocol](https://blog.cloudflare.com/roughtime/). Cloudflare's Roughtime server apparenly responds on [all Cloudflare anycast IPs](https://developers.cloudflare.com/time-services/roughtime/usage/); there is also https://time.txryan.com/. Unfortunately, Roughtime doesn't have any packaged clients; those that exist [simply print epoch seconds on the terminal](https://crates.io/crates/roughenough), requiring manual

```sh
date --utc --set "$(roughenough-client roughtime.int08h.com 2002)"
```

to actually update the clock.

`chronyd` has a special [`-s` flag](https://wiki.archlinux.org/title/Chrony#Example:_intermittently_running_desktops), which restores system time from either RTC or `driftfile`, whichever is newer. It should be enough to fix this problem on devices lacking battery-powered clocks without sacrificing security, assuming they don't stay powered off for too long (6-day certificates are [the new norm](https://letsencrypt.org/2026/03/11/shorter-certs-certbot)).

On the other hand, for systems with battery-powered clocks, fixing NTS bootstrap **masks** the hardware problem: certificates failing to validate is a clear sign one needs to buy a new battery. Because of this, I suggest to move the fix to `ujust`s, since it is useful only for devices without battery-powered clocks. The `ujust` is question should probably be two-level: basic `-s` for devices that don't stay powered off for too long, and plain NTP, for those who really need it. IPv6-only connectivity is next to nonexistent, but it probably makes sense to add an IPv6 NTP server in addition to the already added IPv4, just in case.

Packaging a Roughtime client would fix the problem without sacrificing security, but it is also the most involved solution.

> But this would need to fire before chronyd.service get loaded. I don't know what would be the correct way to do this.

Look no further than chrony's own [`chrony-wait.service`](https://gitlab.com/chrony/chrony/-/blob/master/examples/chrony-wait.service?ref_type=heads).
