### ISSUE TITLE
[FEAT] Default to HTTPS mirrors

### ISSUE THREAD

**Issue by Seirdy** [secureblue/secureblue#276]
**Describe the benefit this feature would provide to the project**
Would provide some confidentiality from untrusted networks regarding which packages are installed on a system during updates.

**Describe the solution you'd like**
A query parameter to specify the preferred protocol when querying mirrors has been supoorted by Mirror Manager 2 since 2016, and has worked well for years. More on the `protocol` query parameter: https://github.com/fedora-infra/mirrormanager2/pull/172

**Describe alternatives you've considered**
None.

**Declaration**
- [X] I declare that I have read the README and my feature request is in-scope.

**Comment by RoyalOughtness** [comment]
@Seirdy thanks for this. A couple things to note first. This should only really matter for layered packages, since the base images are pulled over https from ghcr. Also, mirrormanager isn't used on Fedora atomic, so I think this would mean in the repos, this change for each metalink:

```
metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-debug-$releasever&arch=$basearch
```

would become this

```
metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-debug-$releasever&arch=$basearch&protocol=https
```

If so that seems easy enough. PRs welcome

This has also reminded me to look into checking if the container policy can be hardened and whether the ghcr protocol can be forced:

https://github.com/secureblue/secureblue/issues/278
https://github.com/secureblue/secureblue/issues/277

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/commit/3b9ae540acd7248d1f960a839e2020b9245d6cce
