### ISSUE TITLE
Pop_OS user switching to SecureBlue - Security concerns -

### ISSUE THREAD

**Issue by DimSystem** [secureblue/secureblue#285]
Hi there!

Currently using Pop OS and considering switching to secure blue. I’m interested in its features, but I’m concerned about potential supply chain attacks. eg: targeting the developers on GitHub, that supply the images to users (Recently we thad the XZ Utils attack, on the linux kernel repo).

Are there any security measures in place to mitigate this risk? Additionally, are there ways to verify the integrity (signatures) of the images before installing them? Or between updates?

Thank you!

**Comment by iotku** [comment]
This is an area of relevant interest to me (I run my own image based on BlueBuild as well).

As far as I know the images are [signed with cosign](https://blue-build.org/how-to/cosign/) and rpm-ostree verifies the signatures once you rebase to the ostree-image-signed:... image, everything is processed and signed from within github CI such that everything should match the state of the various repositories (SecureBlue -> BlueBuild (GitHub Acton for building the image) -> Universal Blue -> Fedora Upstream).

As far as I know, through each step of the process everything is signed and verified to match the signatures.

With that being said, I don't see any reasons why a compromised account somewhere in the chain couldn't for instance make a malicious commit which would be reflected in the produced images. In such a case I'm reasonably confident that it would be auditable (would need to commit to a repo to change the images), but I think there's some inherent trust required that nobody is malicious or has their account compromised.

I'm certainly interested if there's more to it that I'm unaware of (quite likely), but regardless it seems to be a relatively transparent process, albeit a little convoluted given the various layers involved.

**Comment by DimSystem** [comment]
> This is an area of relevant interest to me (I run my own image based on BlueBuild as well).
> 
> As far as I know the images are [signed with cosign](https://blue-build.org/how-to/cosign/) and rpm-ostree verifies the signatures once you rebase to the ostree-image-signed:... image, everything is processed and signed from within github CI such that everything should match the state of the various repositories (SecureBlue -> BlueBuild (GitHub Acton for building the image) -> Universal Blue -> Fedora Upstream).
> 
> As far as I know, through each step of the process everything is signed and verified to match the signatures.
> 
> With that being said, I don't see any reasons why a compromised account somewhere in the chain couldn't for instance make a malicious commit which would be reflected in the produced images. In such a case I'm reasonably confident that it would be auditable (would need to commit to a repo to change the images), but I think there's some inherent trust required that nobody is malicious or has their account compromised.
> 
> I'm certainly interested if there's more to it that I'm unaware of (quite likely), but regardless it seems to be a relatively transparent process, albeit a little convoluted given the various layers involved.

Thank you for the answer!
Well, Fedora is not signing their container images, so that part of the chain isn’t locked down, for now (https://universal-blue.discourse.group/t/universal-blue-base-images-are-now-verified-during-the-build-process/329).

And since SecureBlue upstreams the image themselfs to git I'm not sure if the signed image from ublue applies here, since the sig is going to be different already anyways, and signed by them (if I'm not mistaken)...

Would love some feedback from @qoijjj here, since this is quite vital, and if not taken proper care of can jeopardize all of the image's goals.

**Comment by RoyalOughtness** [comment]
Great questions, thank you for raising them. I'll go point by point:

> I’m concerned about potential supply chain attacks. eg: targeting the developers on GitHub, that supply the images to users (Recently we thad the XZ Utils attack, on the linux kernel repo).

This is an apt concern. Unfortunately, there is no panacea for it. What we can do though is apply the following mitigations to reduce the risk as much as possible:

### Supply chain image signatures

All images in the chain are signed and those signatures are validated downstream. So for example for secureblue's wayblue-hyprland-nvidia-hardened image, all of the steps of the image chain are doing signature validation:

1. ublue signs their images [here](https://github.com/ublue-os/main/blob/main/.github/workflows/reusable-build.yml#L223)
2. ublue's hwe repo (nvidia, asus, etc) validates ublue-main's signature from step 1 [here](https://github.com/ublue-os/hwe/blob/main/.github/workflows/reusable-build.yml) and then signs the nvidia image [here](https://github.com/ublue-os/hwe/blob/main/.github/workflows/reusable-build.yml#L268)
3. wayblue verifies the ublue nvidia image signature [here](https://github.com/wayblueorg/wayblue/blob/live/.github/workflows/build.yml#L54) and then signs the resulting image [here](https://github.com/wayblueorg/wayblue/blob/live/.github/workflows/build.yml#L63)
4. secureblue verifies the wayblue image signature [here](https://github.com/secureblue/secureblue/blob/live/.github/workflows/build.yml#L122) and then signs the resulting image [here](https://github.com/secureblue/secureblue/blob/live/.github/workflows/build.yml#L142)

>  Additionally, are there ways to verify the integrity (signatures) of the images before installing them? Or between updates?

This is done by default on secureblue so long as you are on the `ostree-image-signed` registry as instructed in the readme. The container policy is [hardened by default](https://github.com/secureblue/secureblue/blob/live/config/scripts/hardencontainerpolicy.sh#L6) such that only signed images that have been specifically defined in the container policy.json can be used. This applies not only to rpm-ostree image updates and rebases, but also to toolbox and distrobox images. It's for this reason that secureblue sets the distrobox and toolbox defaults [to ublue images](https://github.com/secureblue/secureblue/blob/live/config/files/usr/etc/distrobox/distrobox.conf#L1) since the toolbox and distrobox defaults are unsigned.

So to answer your question, once you've rebased to secureblue on `ostree-image-signed`, your installation has been verified and all subsequent image upgrades will be as well.

### Signed commits

secureblue forbids commits that are unsigned. This is enforced using branch policies. This can be checked by opening the commit history and clicking on the "Verified" badge to see details. This means that the commit has been signed using either a GPG key tied to the account, or using Github's identity system.

### Principle of least privilege

secureblue doesn't permit outside contributors to have any [more access than necessary](https://en.wikipedia.org/wiki/Principle_of_least_privilege). In practice this means that outside contributors only ever get read access. The only person who has the ability to commit to the repo is myself.

### Multi-factor authentication

There's always the risk of my account being targeted though, like you mentioned. I utilize multi-factor auth ([non-SMS](https://en.wikipedia.org/wiki/SIM_swap_scam)) at every step. My github account, my Fedora identity account (used for managing the two COPRs in secureblue), and the email accounts corresponding to those accounts are all backed by independent multi-factor authentication mechanisms. Even my social media accounts tied to these projects (like my discord and reddit) are backed by independent multi-factor auth.

### Auditability

> reasonably confident that it would be auditable (would need to commit to a repo to change the images), but I think there's some inherent trust required that nobody is malicious or has their account compromised.

The image build process at each step is auditable and all logs are public. However, this only does so much. Sure, secureblue and the upstream images are largely just config and simple scripts that anyone can read, but what if a malicious actor with permissions somewhere in the chain slips something in, even temporarily?

The only way I'm aware of to mitigate privileged repo members upstream going rogue is to make sure there are a good number of eyes actually perusing new commits. This can be accomplished by encouraging people to get email notifications for new commits. Especially for repos like ublue's main and hwe that don't get frequent commits, clicking the Watch button and getting emails for new commits/PRs is a good practice.

secureblue is putting every mechanism I'm aware of in place to mitigate the risks here, and yet unfortunately none of it would have prevented the `xz` attack. The biggest threat to the FOSS supply chain has nothing to do with images or even distros. It's the volume of underfunded, thankless volunteer labor going on across thousands of critical projects. When you have a [tragedy of the commons](https://en.wikipedia.org/wiki/Tragedy_of_the_commons) like FOSS, where everyone wants to use software but no one wants to fund it, especially major high value enterprise industry players, those packages become inevitable targets for attack.

What you should do, and in part what secureblue is trying to accomplish, is to assume that at any time there is more than likely a yet undiscovered or undisclosed vulnerability or backdoor in at least one package on your system, and to put measures in place to proactively mitigate the risks across the board for all packages.
