### ISSUE TITLE
[FEAT] PAM Duress Passwords

### ISSUE THREAD

**Issue by DimSystem** [secureblue/secureblue#287]
**Describe the benefit this feature would provide to the project**

We put a lot of effort into security. We require strong password, and more often than we used to we add two-factor/multi-factor authentication to the mix. That’s on top of the firewalls, proxies, and the VPN, and maybe intrusion detection and some others too. 
That makes me wonder if it’s time to borrow an idea from the world of physical security – duress codes. Many alarm systems are configured so that if the duress code is entered the alarm appears to be deactivated but still signals the monitoring center. We could do the same thing for the passwords for key personnel, letting them configure a second password that would be a minor variation of the first – maybe one letter switched from lower to upper case. When activated not only could it send the secret alert, it could activate additional defensive measures.

**Describe the solution you'd like**

[The PAM Duress](https://github.com/nuvious/pam-duress) is a module designed to allow users to generate 'duress' passwords that when used in place of their normal password will execute arbitrary scripts. For quickly wiping all hardware keystore keys including keys used as part of deriving the key encryption keys for disk encryption to make all OS data unrecoverable.
Since this project borrows some features from GrapheneOS, and graphene itself is now using duress passwords, I belive it would be a good add. 

**Describe alternatives you've considered**

The alternative would be a "local fail2ban" but not scope of this feature. 
Basically this suggest an alternative to mitigate, and give yourself alternatives for the infamous "$5 wrench attack".

**Declaration**
- [ x] I declare that I have read the README and my feature request is in-scope.

**Comment by TommyTran732** [comment]
I am not sure how to do this safely, but here is an idea:

- Cause corruption to the LUKS header
- Run trim
- Reboot the computer

But this strategy is just praying that the SSD controller actually trims the old LUKS header. And I am not sure how this even shows up in the UI. It doesn't protect against someone who knows this feature exists and take a backup of the LUKS header either.

**Comment by TommyTran732** [comment]
Another approach is to use TPM unlock for disk encryption, and just wiping the TPM when the duress password is entered.

The problem with this is that, systemd-cryptenroll puts complete trust into the TPM, and is vulnerable to stuff like faultpm. It is not a safe implementation like on Android, or even Bitlocker/ChromeOS encryption. It probably is the better way to go about it though, if there is something in the UI saying "The TPM won't release the secret! Something must be corrupted, and there is no fallback key protector to even try."

**Comment by RoyalOughtness** [comment]
@DimSystem 

I'll summarize the discussion I had with Tommy about this on discord in #dev. On the surface, it seems simple, the login manager just needs to trigger a pam module right? Unfortunately, for several reasons, this is not the case:

1. Since this would only provide duress passwords at the display manager, which is loaded well after the drive is unlocked, an attacker with physical access would still be able to do a cold boot attack on systems without memory encryption, which would be the vast majority of them.
2. Invoking a command to wipe the LUKS header would require detecting the drive type the OS is on (including SATA vs NVMe SDDs vs HDDs, querying for the drive capabilities, and then determining which secure erasure functionality would suffice (e.g. ATA Secure Erase). And even then, on some drives this would be a slow process.

For both of these reasons, implementing duress passwords at the display manager level would provide the illusion of security and serve only to mislead users.

Given this, the logical next step would be to move the duress functionality to the disk unlock screen. However, systemd has no support for this as far as I know. Until and unless that changes, there won't be a way to properly implement this.

> Since this project borrows some features from GrapheneOS, and graphene itself is now using duress passwords, I belive it would be a good add.

On GrapheneOS the OS itself is separate from the encrypted user data, so the OS can be loaded and show the initial unlock screen before any user data is decrypted. This is not the case on desktop linux systems, where the OS itself is in the same encrypted volume as the user's data.

Please reopen this if you encounter any information about systemd/crypsetup implementing duress password support.
