### ISSUE TITLE
Change root shell to dash

### ISSUE THREAD

**Issue by symbiogenesis** [secureblue/secureblue#308]
Ubuntu chose to use [dash](https://packages.fedoraproject.org/pkgs/dash/dash/) as the default root shell a long time ago, largely for performance reasons.

But, one could argue that the smaller attack surface of dash is also a security benefit, because ShellShock proved that bash is not so secure.

The user shell can remain as bash by default.

I have been able to use it without problems with something approximating a secureblue setup.

**Comment by wandapeter** [comment]
I am unable to think of any benefits, please state some examples? 🙂

**Comment by symbiogenesis** [comment]
The lack of CVEs in dash compared to bash is the logic. It is more secure because it actually does less. It was not vulnerable to ShellShock.

But, because Ubuntu uses it for the root shell, most important upstream packages are well-tested against it. 

Users who want to run scripts as root should just use the user shell with sudo, run0, or sudo-rs and thus their scripts shouldn't be affected.

**Comment by RoyalOughtness** [comment]
CVE counting is very misguided. This is the same tired argument of “use musl / openrc / runit / libressl / doas / whatever instead of the alternative because it has fewer CVEs and a smaller codebase”. CVE disclosures  (not the underlying vulnerabilities) are a good thing. It means that the right people are scrutinizing the project and uncovering vulnerabilities. A project that is widely used and well scrutinized with a high rate of CVE disclosure is infinitely preferable to a rarely used and unscrutinized project with few CVEs.

Also, installing a second shell and using different shells for the user and root assumes there's a clear boundary between root and non-root. [There isn't](https://madaidans-insecurities.github.io/linux.html#root). As such, installing another shell would increase the system's attack surface.
