### ISSUE TITLE
[FEAT] add a ujust audit-flatpak script

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#337]
to help detect insecure flatpak configurations:

- presence of unverified flathub
- presence of network permission
- presence of x11 permission

**Comment by secretmango** [comment]
good idea!

Additional points:

```
[Context]
filesystem=!home,!host
sockets=!x11;!pulseaudio;
shared=!ipc;
```

then access to `~/.local/share/flatpak/overrides` and to the `org.freedesktop.flatpak`  session (or system?) bus and the `flatpak-spawn` permission.

Not sure how to detect the last ones.

The script could then echo the apps name with a warning, it should not do anything with the permissions. The Flathub people are now more strict when submitting, [as can be seen here](https://github.com/flathub/flathub/pull/5233).

I will see if I can make a prototype.

---

Btw. how will secureblue handle system vs. user flatpak remote? A system remote may be needed in the future for flatpak systemd-sysextensions. This may not matter on uBlue, as rpmfusion can be used, but it is a deviation from upstream, and sysextensions could mean more stability and maybe security.

**Comment by RoyalOughtness** [comment]
> This may not matter on uBlue, as rpmfusion can be used

what does rpmfusion have to do with flatpak?

**Comment by secretmango** [comment]
@qoijjj ostree/image-based distros have the issue that hardware and proprietary software compatibility can not be configured by default, by Fedora.

This means, users of the vanilla atomic desktops would need to layer packages from rpmfusion to get basic NVIDIA functionality, not to mention all the uBlue hwe things not included.

It is very arguable if that level of minimalism, which is not always legally required, makes sense for atomic distros. 

Coming from this issue, [systemd sysextensions](https://www.freedesktop.org/software/systemd/man/latest/systemd-sysext.html) are an upcoming technology that allow the installation of system components without layering. I read that flatpaks can be used as a delivery method.

I assume (with pretty high confidence) that this would only be possible with system flatpaks though, as these are installed on the system.

---

This does not ***directly*** apply to uBlue and thus secureblue, as they just add packages from rpmfusion. There are potential issues here though.
- some time in the future, Fedora may ditch the traditional variants
- rpmfusion is a community project, not assiciated with Fedora. All Redhat devs working there are doing that secretly afaik. This means rpmfusion could have pretty big problems with sustainability.
- The chain of trust is also less secure when relying totally on a community project, serving kernel modules. Just have to drop the name "xz" to stress that this is a huge issue, and xz is a userspace component.
- when Fedora focuses primarily on atomic variants (which will be years from now), as the UX of using rpmfusion on atomic is so bad (layering by default), it may be very likely that rpmfusion gets less attention
- systemd sysextensions could be like flathub, a central way where packages can be packaged once and thus ensuring a shorter chain of trust, faster updates and maybe even less privileges due to isolation

Speaking of ublue, it could be an idea to use Fedoras OCI images directly, to reduce the chain of trust. But this wouldnt mean, it would be more problematic to add rpmfusion packages.

These were the points for the future I am thinking of. That all aside, allowing any user to install any executable code may also be problematic. But as `bash script.sh` always works, making a noexec homedirectory "security theatre",  this does not matter without major architectural changes in the Linux Desktop.

**Comment by secretmango** [comment]
I see how this is off-topic for this issue though. I could move it to another one.

**Comment by RoyalOughtness** [comment]
> ostree/image-based distros have the issue that hardware and proprietary software compatibility can not be configured by default, by Fedora.

this has nothing to do with them being image based. the same is true on workstation

I'm lost as to how any of this relates to this issue or even secureblue for that matter

**Comment by secretmango** [comment]
It matters especially for Atomic Fedora as installing an rpm vs. installing a systemd-sysextension is not a big difference on traditional Fedora, while layering highly increases update times (and may break future integrity check mechanisms too)

I also mentioned the impacts for secureblue / security in general

**Comment by RoyalOughtness** [comment]
I'm still completely lost as to how any of this relates to a script to audit the permissions currently granted to flatpaks installed on the system. It seems like it doesn't. Let's keep things on topic please

**Comment by fine2006** [comment]
> good idea!
> 
> Additional points:
> 
> ```
> [Context]
> filesystem=!home,!host
> sockets=!x11;!pulseaudio;
> shared=!ipc;
> ```
> 
> then access to `~/.local/share/flatpak/overrides` and to the `org.freedesktop.flatpak` session (or system?) bus and the `flatpak-spawn` permission.
> 
> Not sure how to detect the last ones.
> 
> The script could then echo the apps name with a warning, it should not do anything with the permissions. The Flathub people are now more strict when submitting, [as can be seen here](https://github.com/flathub/flathub/pull/5233).
> 
> I will see if I can make a prototype.
> 
> Btw. how will secureblue handle system vs. user flatpak remote? A system remote may be needed in the future for flatpak systemd-sysextensions. This may not matter on uBlue, as rpmfusion can be used, but it is a deviation from upstream, and sysextensions could mean more stability and maybe security.

I think we can use the hardening recommendations from https://privsec.dev/posts/linux/desktop-linux-hardening/#flatpak for the permissions to check for
