### ISSUE TITLE
[BUG] Error joining the Discord channel

### ISSUE THREAD

**Issue by secretmango** [secureblue/secureblue#351]
In one thread a discord message was linked as the only way to access that information.

I created a Discord Account (which is really hostile against VPN users...) and tried to see that chat, did not work. Tried to join the channel via the given link, also did not work.

"Could not take invitation"

Any idea why?

**Comment by RoyalOughtness** [comment]
https://github.com/secureblue/secureblue/issues/194

**Comment by secretmango** [comment]
that was the link I used. Tried again, still the same error. Discord is not usable with a VPN, even after solving many captchas and verifying a phone number and mail address

Would be happy if you could quote the hacky workaround to reinstall an app that was formerly override-removed. That info is otherwise not available.

**Comment by RoyalOughtness** [comment]
I assumed when you said "discord is hostile to vpn users", you meant you had already disabled it with that in mind. You know what the problem is and know that the solution is to disable your VPN. You are making your personal decisions other people's problem. This is your second formal warning to stop the entitled behavior. Cut it out.
