### ISSUE TITLE
io_uring status

### ISSUE THREAD

**Issue by symbiogenesis** [secureblue/secureblue#444]
io_uring is disabled with secureblue by default. It seems like an awesome feature if and when the security issues are resolved. Those issues have been a top priority for many smart developers.

My question is whether there is a particular metric we can use to gauge whether io_uring is secure enough to enable?

i.e. if and when it is no longer a significant source of submissions to the Google Vulnerability Rewards Program, or when Google starts to enable it by default in their products, or something else

**Comment by RoyalOughtness** [comment]
It's not so much about "security issues are resolved". The known vulnerabilities are already resolved. We disable it because (and the reason the sysctl was created in the first place) it has been demonstrated as a significant source of attack surface: https://lore.kernel.org/lkml/20230629132711.1712536-1-matteorizzo@google.com/T/

> My question is whether there is a particular metric we can use to gauge whether io_uring is secure enough to enable?

I would contest with the language of "secure enough" as I don't think that asks the right question. That aside, some "metrics" to use would be:

1. Does io_uring enable significant attack surface?
2. Do the kernel maintainers still maintain a sysctl for it?

> it is no longer a significant source of submissions 

CVE counting isn't a good source of information. It's more a measurement of how actively a feature is used by projects than anything else.

Overall though I get the impression that you fundamentally misunderstand the purpose of this project. If your goal is to simply ensure that all **known** vulnerabilities are patched on your system, you don't need secureblue. Fedora already does this. secureblue's goal is to go well beyond this and (as the scope says) defend against not just known but also **unknown** vulnerabilities. You are thinking only of the known security issues, which are quickly patched. There are almost certainly many unknown security vulnerabilities on your system right now, waiting to be discovered and disclosed by a security researcher. Whether you want to reactively wait for them to be disclosed and patched or proactively defend against them is up to you 🙂
