### ISSUE TITLE
[FEAT] real-ucode

### ISSUE THREAD

**Issue by lucasmz-dev** [secureblue/secureblue#455]
**Describe the benefit this feature would provide to the project**
Updates to microcode when the user does not have their UEFI updated (either from not knowing, or because it doesn't receive updates anymore and are thus unavailable).

**Describe the solution you'd like**
Divested Computing Group has [real-ucode](https://github.com/divestedcg/real-ucode), this could be used or repackaged, not sure.

**Describe alternatives you've considered**
None :P 

**Declaration**
- [x] I declare that I have read the README and my feature request is in-scope.

**Comment by RoyalOughtness** [comment]
I've seen that repo before, but the claims it makes appear to simply not be accurate.

The linux firmware repo has microcode for non-enterprise platforms:
https://gitlab.com/kernel-firmware/linux-firmware/-/tree/main/amd-ucode?ref_type=heads
>This repository includes microcode container files for family 15h, 16h,
17h, and 19h AMD CPUs. Microcode patches for families earlier than 15h are
included in the microcode_amd.bin microcode container file. The microcode
patches included in an AMD CPU microcode container file can be listed using
the script in the following git repository:
https://github.com/AMDESE/amd_ucode_info

And the [linked issue](https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/issues/10) for intel microcode was closed years ago and many new platforms have been added since:

https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/commit/3f97690f0da8011f52209b232450a1e5c4f2e1f6#diff-33de869c8a5b3a9d8fba9504aa6ef92ad60c352a3de4b0e362238b92888c1b0e
https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/commit/925555515555dfcfafd4997f39459967c33dc5d5#diff-372b09c566e29830b022bdfca0bc8c224f9428006cab2d7a308bc0582636e550
https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/commit/262f0c97f2fbc3839a59523cc6c6bcf500e2850b#diff-2560c6d76400204dfdd0fb35de77b49369f50e659f22ce82fabfc96c703fdc87
https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/commit/2be47edc99eeeb5b6d76bf9450b74747cdaf3263#diff-021d86d1ec0affa743f55641dbe31c807a9b2596bc883fa2faf19573d695c476
etc

In short, it appears to me that that repo is now obsolete thanks to upstream changes.

**Comment by lucasmz-dev** [comment]
For AMD, it did seem to have an effect for me. I have a Ryzen 5 5600G, and before installing it, I got two known vulnerability warnings when running `sudo dmesg | grep microcode`, after doing so + running `sudo dracut -f` (all instructions from them) and restarting, I no longer had those warnings and got another message saying "Updated early to (new microcode version)".  Of course, all this was before updating my BIOS.

I would show you a screenshot as evidence but I unfortunately did not take one 🫥

**Comment by RoyalOughtness** [comment]
Strange. That cpu is Zen3 I think, which is included according to the readme in that repo.

You may which to report this issue here: https://bugzilla.redhat.com/buglist.cgi?bug_status=__open__&component=linux-firmware&product=Fedora&product=Fedora%20EPEL&query_format=advanced

**Comment by SkewedZeppelin** [comment]
You can directly compare the index files to see that is is very useful.

linux-firmware only has support for 41 AMD cpuids, most recent of which are solely enterprise chips: https://github.com/divestedcg/real-ucode/blob/master/index-amd-official.txt

linux-firmware doesn't even have zen5 at all (fam1ah)

real-ucode has support for 106: https://github.com/divestedcg/real-ucode/blob/master/index-amd.txt

you can also see that many of the ones in linux-firwmare are not even the most recent via the `Last` column of the index

real-ucode has repeatedly proven useful in patching issues such as zenbleed and sinkclose on systems before the vendor provided bios updates, if they even did at all.

**Comment by SkewedZeppelin** [comment]
as for intel their official microcode repository has 290 cpuids, 120 of which are not the latest version: https://github.com/divestedcg/real-ucode/blob/master/index-intel-official.txt

real-ucode has 615 cpuids supported, only 2 of which are not the latest version: https://github.com/divestedcg/real-ucode/blob/master/index-intel.txt

the indexes exist purely for this purpose of proving the use.

**Comment by RoyalOughtness** [comment]
@SkewedZeppelin thanks for the additional details

I'm curious why Fedora's official firmware packaging is missing so much stuff 🤔 

Are there licensing considerations?

**Comment by SkewedZeppelin** [comment]
AMD and Intel do it purposely for market segmentation

no distro will ship a third party repository for this due to risk (especially with today's amd vuln)
and no distro will pull these proprietary files from somewhere without an explicit license

**Comment by RoyalOughtness** [comment]
@SkewedZeppelin oh. I see now. so this is a matter of intel/amd getting their ucode into linux-firmware? Why aren't they doing this and where is real-ucode sourcing this if not from official sources?

**Comment by SkewedZeppelin** [comment]
> getting their ucode into linux-firmware

they do not want to.

> doing this 

because they want more money.

you can see this in any amd security advisory, they provide updates via microcode for enterprise and only agesa/efi updates for consumer
and enterprise gets them 2-3 months before consumer

example: https://www.amd.com/en/resources/product-security/bulletin/amd-sb-7014.html
enterprise:
> AMD EPYC
> μcode
>  2024-05-03

consumer:
> CLIENT/DESKTOP
> ComboAM5PI
> 2024-08-07


yet if you check the dates on the microcode in such agesa update, it lines up with the same week as enterprise
so they make them all at once, but push them out slower

ie. making enterprise platform ucode easily available and hot loadable encourages cloud providers to purchase enterprise chips
making consumer platform ucode only available via agesa updates slowly available via vendors and requiring a reboot discourages them from building fleets of systems with cheaper consumer chips


> official sources

[platomav](https://github.com/platomav/CPUMicrocodes) extracts them from efi updates scraped via lvfs and other sources

real-ucode just converts them into the loadable format used by eg. dracut

**Comment by RoyalOughtness** [comment]
@SkewedZeppelin gotcha. 

Worth looking into, although pulling binary files from the unofficial platomav repo is fairly spooky :smile: , both from a trust perspective and a licensing perspective

we just removed fedora logos from secureblue in large part to comply with fedora trademark policy. this kind of thing is something that would apply to secureblue too:


> and no distro will pull these proprietary files from somewhere without an explicit license



> you can see this in any amd security advisory, they provide updates via microcode for enterprise and only agesa/efi updates for consumer
>and enterprise gets them 2-3 months before consumer

don't the efi updates include microcode updates though? or are you saying that's the issue: that the consumer needs to keep their agesa/efi up to date to stay on top of microcode?

also, are you saying that `lscpu` on consumer hardware is mistaken when it reports microcode mitigations?

**Comment by SkewedZeppelin** [comment]
> their agesa/efi up to date to stay on top of microcode

yep, but the issue here is so many vendors do not provide updates for their products
I have many systems that still receive new microcode but haven't seen an efi update in 2 years
other systems may only provide 1-2 efi updates a year
only some systems are lucky to get them 3-4 times a year

the whole point of real-ucode is to side step this market segmentation issue and also sidestep the vendor delay

> reports microcode mitigations

those are accurate but lscpu doesn't account for many issues such as sinkclose

> unofficial platomav repo is fairly spooky

all of them are signed in theory to prevent loading untrusted microcode
issues like https://github.com/google/security-research/security/advisories/GHSA-4xq7-4mgh-gp6w aside

> licensing perspective

this is totally understandable however both do allow redistribution:

https://github.com/divestedcg/real-ucode/blob/master/LICENSE.intel-ucode
> Redistribution and use in binary form, without modification, are permitted, provided that the following conditions are met

https://github.com/divestedcg/real-ucode/blob/master/LICENSE.amd-ucode
> to any person obtaining a copy of this microcode in binary form (the "Software") ("You"), to install, reproduce, copy and distribute copies of the Software and to permit persons to whom the Software is provided to do the same
