### ISSUE TITLE
[feat] create ujust debug-dump

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#479]
For troubleshooting user issues, should just dump the output of `rpm-ostree status`, `rpm-ostree kargs`, hardware info, `nvidia-smi`, etc to a pastebin

**Comment by mintpilo** [comment]
Instead of dumping to a pastebin directly, maybe it might be more useful to `cat` to a text file in the current directory?  They could attach this directly in the discord or upload to a pastebin after.

Edit: I guess an upload could be an optional [y/N] after running all commands, and telling the user it was saved to [filename].txt
