### ISSUE TITLE
[feat] add motd warning for users who have no tags

### ISSUE THREAD

**Issue by RoyalOughtness** [secureblue/secureblue#519]
currently we use ` split(":")[-1]'` to pull the image name 

if users forget to use a tag, this will break: https://github.com/secureblue/secureblue/issues/517

**Comment by spaceoden** [comment]
quick and dirty check: `if [ -z "$(rpm-ostree status | grep 'hardened:')" ] ; then echo 'you are not using a tag' ; fi`
this searches the output of rpm-ostree status for `hardened:`, because all our images end in "hardened" and when no tag is selected, the colon is not present.

I'm not certain how to implement it yet.
