### ISSUE TITLE
Refactor to align more with upstream structure

### ISSUE THREAD

**Issue by wandapeter** [secureblue/secureblue#54]
Maybe move *-packages.yml files into the modules folder

**Comment by wandapeter** [comment]
Also move script module section into one imported file

**Comment by RoyalOughtness** [comment]
> Maybe move *-packages.yml files into the modules folder

This is not correct. Please see the modules readme, the packages files are in the correct place

> The value should be a path to a file inside the `config` directory.
https://github.com/ublue-os/startingpoint/blob/template/config/README.md?plain=1#L29

**Comment by RoyalOughtness** [comment]
> Also move script module section into one imported file

This will not be done. Keeping files that have distinct and unrelated functionality separate is a best practice.

**Comment by wandapeter** [comment]
> > Maybe move *-packages.yml files into the modules folder
> 
> This is not correct. Please see the modules readme, the packages files are in the correct place
> 
> > The value should be a path to a file inside the `config` directory.
> > https://github.com/ublue-os/startingpoint/blob/template/config/README.md?plain=1#L29

You're right. My mistake. I misunderstood the documentation.

**Comment by wandapeter** [comment]
> > Also move script module section into one imported file
> 
> This will not be done. Keeping files that have distinct and unrelated functionality separate is a best practice.

Since the script calls in each recipe are the same, i would extracted them into one file. In my understanding, "non-unique" is not distinct. Also reducing redundancy is a best practice too.

Idk it's not a hill i'll die on but i'd disagree with this approach except distinct script calls are planned in the future.

**Comment by RoyalOughtness** [comment]
> Since the script calls in each recipe are the same, i would extracted them into one file. 

This is not a practice done anywhere else. If you have a java project for example, you don't combine your utils into one file just because there are import calls referencing them in multiple files. You keep them separate for organizational purposes. 

> "non-unique" is not distinct.

I'm not sure what this means

>  Also reducing redundancy is a best practice too.

The redundancy here is not caused by having multiple scripts. It's caused by yaml not supporting any kind of import or include. The real solution here isn't to combine scripts, but to incorporate [pyyaml-include](https://github.com/tanbro/pyyaml-include) into the project to enable yaml refactoring which would solve all kinds of yaml redundancy not just the scripts.

This is something that likely belongs upstream. However, it's not really a priority for me. I'm not at all opposed to it though if you're going to work on it.

**Comment by wandapeter** [comment]
I am not talking about combining scripts into one single file. 

I mean the following, which is tested and working:

replacing 
```
 - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
      - cron.sh
      - chromium.sh
```
with 
```
  - from-file: ../modules/scripts.yml
```
modules/scripts:yml:
```
type: script
scripts:
  # this sets up the proper policy & signing files for signed images to work
  - signing.sh
  - cron.sh
  - chromium.sh
```

doing this not only with the scripts but with bling and files would greatly reduce redundant configuration in the different recipes and make maintaining it much easier / the repo cleaner.

**Comment by wandapeter** [comment]
also i am not sure if using the modules directory is intended but my point is splitting the configuration into files

**Comment by RoyalOughtness** [comment]
Oh! I misunderstood. Yes that's fine, please go ahead.
