### ISSUE TITLE
Are custom font installs in scope?

### ISSUE THREAD

**Issue by wandapeter** [secureblue/secureblue#55]
I am not sure if the custom font installs are in scope bc they do not provide any security functionality

**Comment by RoyalOughtness** [comment]
Just to be clear, this project is based on ublue, which itself doesn't add security functionality on top of regular silverblue and kinoite images. So already we are pulling in ublue addons for usability improvements via packages (codecs, ffmpeg, nvidia drivers) that can't otherwise be included in the regular silverblue and kinoite images for legal reasons. Do these packages improve security? Nope. Do they degrade security? Nope. Do they dramatically improve usability? Yep. The only difference with the fonts is that they're provided via ublue's [bling](https://github.com/ublue-os/bling) instead of being baked into the images.

So as a general rule, as long as something isn't causing a security degradation, it's not necessarily excluded from this repo.

However, in this case I think the fonts can be removed because they are simply too opinionated, not because of their lack of security value. Feel free to remove them.

**Comment by wandapeter** [comment]
Understood. I'll create a PR.
