### ISSUE TITLE
[FEAT] Disable user list on login screen (GNOME)

### ISSUE THREAD

**Issue by solidc0re** [secureblue/secureblue#636]
**Describe the benefit this feature would provide to the project**
Hide usernames from the GNOME login screen for obfuscation purposes, in case someone gains physical access to the machine.

**Describe the solution you'd like**
See [here](https://help.gnome.org/admin/system-admin-guide/stable/login-userlist-disable.html.en)

**Describe alternatives you've considered**
n/a

**Declaration**
- [x] I declare that I have read the README and my feature request is in-scope.

**Comment by RoyalOughtness** [comment]
There are a couple things about this that make it fairly dubious. One is that the display manager is a fairly weak barrier to begin with. The barrier to the data on the disk is the unlocking of the LUKS device.

Second, we already have brute force protection for account passwords via pam faillock. 

Third, usernames aren't stored in a secret way on the disk. Once the LUKS device is unlocked, the data can be read from the disk, including /etc/passwd, which contains all of the users on the machine. 

As such this would be increasing user inconvenience for essentially zero security benefit.

**Comment by RoyalOughtness** [comment]
Side note:

Suggestions that involve obscurity as a security technique are often dismissed simply for involving obscurity (since security by obscurity is nonsense[1]). While this is often a correct dismissal, I find Daniel Miessler's method [2] more thorough. His method for determining whether a security technique is `security by obscurity` involves these questions:

1. Is the process of the technique known?
2. Is a key or bruteforce required to break the technique?

If both answers are YES, then the technique is not `security by obscurity`. If either answer is NO, then the technique is `security by obscurity`.

So in this case, for username obfuscation:

1. Is the process of the technique known? -> **YES**, both GDM and posix user management are publicly documented
2. Is a key or bruteforce required to break the technique? -> **NO**, since the primary user account can be found by simply reading the 1000:1000 user from /etc/passwd

It follows then that this technique is `security by obscurity` and is therefore moot.


References:
[1] https://en.wikipedia.org/wiki/Kerckhoffs%27s_principle
[2] https://www.youtube.com/watch?v=V2X0twHBGqE

**Comment by RoyalOughtness** [comment]
One other thought experiment would be: what can we change about the suggested technique to make it not `security by obscurity`? 

Since the issue with the technique was:

```
the primary user account can be found by simply reading the 1000:1000 user from /etc/passwd
```

We could mitigate this by simply creating as many posix users as possible (up to something like 10^18 on 64 bit? you'd run out of disk space before running out of users 😄), and then use a random number generator to arbitrarily pick one as your primary user.

In this case, since a brute force would be required to break the technique (the attacker would have to try up to 10^18 accounts), both answers to the question would become **YES** and the technique would no longer be `security by obscurity`. 

But this is of course highly impractical 🙂

**Comment by solidc0re** [comment]
I appreciate you taking the time to consider the feature request.

My thinking is somewhat different: this is about increasing the complexity and stages through which someone has to jump to gain access.

You see, most theft is opportunistic. Take mobile phones as an example - the PIN is shoulder-surfed, the phone snatched, and now someone has access to your device and its contents. Before you know it they've drained your bank account. It's the main reason why reusing PIN numbers, especially for banking apps, is not recommended.

Laptops are increasingly commonplace, with people often seen using them on public transportation, and in cafes and libraries. Stealing a laptop is very straightforward and the contents of the disk already unencrypted, as the device is active. Sure - computer passwords tend to be more complex as they are typed in using a keyboard (and not a numpad as per the phone example), but if someone is targeted for theft (not government surveillance, espionage etc.) and they reuse their passwords or the password is gleaned from video footage, then it's trivial to gain access to the device for someone with little technical knowledge. The point being that a thief without sufficient knowledge of linux/posix would struggle if they had to figure out the username, even if they already had the password.

At the very least, it would add a hurdle which would buy some time, and gaining additional time is important in criminal investigations because it increases the chances of retrieving the device before any sensitive data is compromised.

I'm not writing this to change your mind; I'm merely writing it to explain my reasoning behind suggesting it.

On a related note, it's also possible to change the displayed username on the lockscreen in GNOME, without changing the username itself, thereby completing the facade.

**Comment by RoyalOughtness** [comment]
> The point being that a thief without sufficient knowledge of linux/posix would struggle if they had to figure out the username, even if they already had the password.

I think this is highly unlikely. Someone who is sophisticated enough to observe/record a password being typed in is sophisticated enough to figure out a username by observation. Usernames aren't treated as secret by the system. They are displayed on screen when a terminal is opened, when polkit is displayed, etc. Most users also choose simple usernames that are either their real name or an alias they commonly use. Any attacker sophisticated enough to shoulder surf a password would observe the username as part of the process. Usernames also have no brute force protections, passwords do. Treating usernames like a second password, with fewer protections, doesn't really make sense. A password is already `something you know`. If you want to make it harder to get past GDM, you would want to add `something you are` and/or `something you have`, aka https://support.yubico.com/hc/en-us/articles/360016649099-Ubuntu-Linux-Login-Guide-U2F or a fingerprint reader. Adding a `ujust` command to automate this process would be in-scope.

In any case, for determining whether future suggestions constitute security by obscurity, we can use Daniel Miessler's method I mentioned above:

```
Is the process of the technique known?
Is a key or bruteforce required to break the technique?
```

And if either answer is no, then we should look for alternative hardening mechanisms. I agree with you that GDM/login could use some hardening, just not by obscurity. There are the pam u2f / fprint methods I mentioned above, and also this article which was suggested by @mintpilo in discord, which isn't about GDM per se but about integrating existing components in a more secure way:

https://0pointer.net/blog/authenticated-boot-and-disk-encryption-on-linux.html
