### ISSUE TITLE
nvidia optimus is gone?

### ISSUE THREAD

**Issue by Bammede** [secureblue/secureblue#679]
I can not find `nvidia optimus` ujust toggle as well as info on Post_install page about nvidia optimus. Is it gone forever?

Secureblue Silverblue

**Comment by RoyalOughtness** [comment]
The `ujust` command is gone, mostly because what it did was only effective on a small subset of optimus hardware. On other hardware it would have a negative or neutral effect. This is in large part because Nvidia has failed to maintain their drivers properly for older optimus hardware.

Please consult the following for Optimus info:

https://github.com/secureblue/secureblue/wiki/NVIDIA-hardware%E2%80%90specific-recommendations

Read this one carefully, it's only applicable and required for specific architectures: https://download.nvidia.com/XFree86/Linux-x86_64/565.77/README/dynamicpowermanagement.html#DriverSettingsfe624
