### ISSUE TITLE
Disable thumbnailing in KDE's Dolphin

### ISSUE THREAD

**Issue by nihil-admirari** [secureblue/secureblue#689]
> GNOME also provides [thumbnailer sandboxing](https://gitlab.gnome.org/GNOME/gnome-desktop/-/issues/213) in Gnome Files, which mitigates attacks [via thumbnailers](https://scarybeastsecurity.blogspot.com/2016/11/0day-exploit-compromising-linux-desktop.html).

Is it enough to place:

```ini
[InformationPanel]
previewsShown=false

[PreviewSettings]
Plugins=
```

in `dolphinrc` to mitigate thumbnailer attacks on KDE?

**Comment by RoyalOughtness** [comment]
Is this a question or a suggestion?

**Comment by nihil-admirari** [comment]
Both. I don't know whether this is a sufficient mitigation. If it is: why not adding?

**Comment by mintpilo** [comment]
*Personally*, this seems like it would go againist "Avoid sacrificing usability for most use cases where possible.", considering that having thumbnails is a pretty expected usecase. 

Hardening should be applied where possible, but if you're trying to solve certain architectural problems without regard to usability... Why not just chuck KDE Plasma images out altogether? (Until they at least have support for screencopy permissions) You're already making a few sacrifices by choosing to use KDE Plasma as I see it. (And certain niche features that do pose a significant security concern, such as GHNS, are disabled already.)

**Comment by RoyalOughtness** [comment]
I concur entirely with @mintpilo 

GNOME is recommended because they have a solution that mitigates the issue *without* disabling thumbnailing. Until KDE achieves parity with this (and the screencopy vulnerability), implementing hacks that the user is more than likely to simply disable accomplishes very little. The solution here is to use GNOME until Plasma catches up.
