### ISSUE TITLE
Threat model

### ISSUE THREAD

**Issue by wandapeter** [secureblue/secureblue#9]
Currently the wording used in the documentation is `some hardening` and `partially hardened without sacrificing usability`. I think such unspecific descriptions are a bad practice. I think one thing to better the documentation and sharpen the general direction of the development would be to define a threat model.

This is especially important if the OS is to be accessible to a broader audience. One thing which for instance is clear, is that secureblue does not feature any anonymity features. 

What else does secureblue not protect against, will never protect against? And protection against what is the goal?

Some of my thoughts:

1. The Browser, arguably the scariest endpoint in everyday use,  is addressed by including a more frequently updated Chromium version. But no further hardening is configured. (disalbing JiT, disabling WASM, WebGL etc.) One idea could be to include Firefox with a hardened user.js to greatly increase browser security.

2. One other possible thing which could be a part the threat model is protection against physical access. For me personally this is even the most important feature of my daily device. (maybe other than browser sec). The current features for this are inconsistent. For instance there are proper kernel parameter set but no PAM hardening is configured. And there is not any mentions how to harden grub. Another thing to consider would be the inclusion of USBGuard.

In general i think the list of features is really good and extensive. One rule of security is to allways consider the balance between protection and "ease of use". And i think the approach of secureblue does that really well. Not unlike great projects like GrapheneOS. Sorry for the long text :-). I just think having a clear threat model would help shaping the project a lot!

**Comment by RoyalOughtness** [comment]
Great points, I'll respond to them individually:

> Currently the wording used in the documentation is `some hardening` and `partially hardened without sacrificing usability`. I think such unspecific descriptions are a bad practice. I think one thing to better the documentation and sharpen the general direction of the development would be to define a threat model.
> 
> This is especially important if the OS is to be accessible to a broader audience. One thing which for instance is clear, is that secureblue does not feature any anonymity features.
> 
> What else does secureblue not protect against, will never protect against? And protection against what is the goal?

This is true and I'll work on improving the documentation there. To be clear though, the goal of this project is akin to GrapheneOS and Kicksecure. Specifically, to increase defense against the exploitation of both known and unknown vulnerabilities.


> 1. The Browser, arguably the scariest endpoint in everyday use,  is addressed by including a more frequently updated Chromium version. But no further hardening is configured. (disalbing JiT, disabling WASM, WebGL etc.) 

Agreed. Additional mitigations to chromium are in-scope for this project, they just need to get done. The ideal solution would be to build, package, and copr an rpm build of [Vanadium](https://github.com/GrapheneOS/Vanadium/). 

>One idea could be to include Firefox with a hardened user.js to greatly increase browser security.

Even if user.js changes had a significant impact on security (and to my understanding they are mostly just "privacy" changes), no quantity of user.js changes brings Firefox up to par with Chromium's security features. https://madaidans-insecurities.github.io/firefox-chromium.html


> 2. One other possible thing which could be a part the threat model is protection against physical access. For me personally this is even the most important feature of my daily device. (maybe other than browser sec). The current features for this are inconsistent. For instance there are proper kernel parameter set but no PAM hardening is configured. And there is not any mentions how to harden grub. Another thing to consider would be the inclusion of USBGuard.

PAM hardening and GRUB hardening are in-scope, they just need to be worked on. USBGuard is in-scope as well so long as it's disabled by default.

I've added the following Roadmap issues to track each of your suggestions. If you start working on one of them, please let me know and I'll assign it to you:

https://github.com/orgs/secureblue/projects/1/views/1?pane=issue&itemId=45562530
https://github.com/orgs/secureblue/projects/1/views/1?pane=issue&itemId=45562531
https://github.com/orgs/secureblue/projects/1/views/1?pane=issue&itemId=45562532
https://github.com/orgs/secureblue/projects/1/views/1?pane=issue&itemId=45562559

**Comment by boredsquirrel** [comment]
Please note that Madaidans Article is now pretty old. Many issues still persist, but 3 or so of the linked ones where closed 5mo ago, due to being solved.

I tried the distro and I am very thankful for your efford!

But I too have a problem with its usability.

It is not clear if these user namespaces are still a real problem. [In this thread](https://github.com/containers/podman/issues/20720) two Podman developers said that they don't see it as a security risk. Do with that what you want, these where not yet in depth answers, but just so you know. 

Flatpak uses Bubblejail, which ironically Madaidan recommends. Why disable it, how are users supposed to get their apps? Flatpaks have the possibility to be very secure and easily sandboxed. Isolate from the core system, thus allowing independend and hourly updates (setting in ublue afaik). Flatpaks are great and if you want it or not, the future of the Linux Desktop. Fedora will not develop Libreoffice anymore, just as an example.

I see that this could be some kind of ChromeOS, but this is simply not what normal (especially Linux) users use their Desktop like. A Browser, even if it has webapps (another thing against Firefox), is no replacement for real Programs like

- GIMP, Inkscape, Krita, ...
- Libreoffice, ...
- KDEnlive
- Thunderbird Mail
- KeepassDX, Cryptomator
- Syncthingy
- element desktop / signal desktop / anything else
-

Using Chromium or Electron for everything puts intense trust in Google and I understand that many people dont like this. Also, Chrome will disable Adblocking soon, what then? I was never hacked through Firefox and I don't really value these dangers high. 

But I see a privacy vs. Security issue here. One could say Thunderbird is less secure than some random webmail through Chromium. Or maybe some Electron app. But I suppose Thunderbird is local, very private and allows addons like Ublock.

In my eyes and the ones of other people, its better just to use noscript, have a hardened Firefox (which decreases the attack surface), official Fedora Build with full SELinux Profile and ublue codecs and all. It works, you can load DRM on demand, which is also a security point in my opinion, you can use Noscript and UBlock forver, and it really is secure enough.

RPM Firefox from Fedora is also the fastest, apart from the single binary from Mozilla, I benchmarked them all basically. It is also said to be more secure than the Flatpak, so keeping it preinstalled... should be an option.

I see how this softens the security already, but this is not Android/GrapheneOS (where I run Mull too, as Vanadium sucks for UX). You cannot simply install any app you want.

----

So my ideas:
- keep firefox
- keep flatpak
- keep flatpak autoupdates
- keep discover, remove the rpm-ostree backend as these go automatic and slow it down a lot
- maybe preinstall the flathub-verified subset by default, this is "the most secure" probably. Some projects are perfectly fine though and not in there, like VLC, which just repackages the binaries
- maybe preinstall rust and cargo?
- if nix could work, this could be an alternative. But this involves having it in /var/nix and linking it to /nix or something similar, which may be out of scope

Some other nice tools or settings to try out would be bubblejail and [SELinux Confined Users](https://fedoraproject.org/wiki/SELinux/ConfinedUsers), but this is a Desktop Task, I think GNOME works already? Plasma just seems to do weird things.

For bubblejail maybe contact @rusty-snake, they seem to know the project and made an RPM spec file that builds fine locally but not on COPR for some reason. [This is my experimental COPR using their spec files](https://copr.fedorainfracloud.org/coprs/boredsquirrel/rustysnake-fedoraextras/packages/)

hardened networkmanager and systemd-resolved is important. Mac address randomization bloats the DHCP channel of wifis though, which may result in very bad behavior, so some GUI switch needs to be there, maybe a specific app for this distro?

opening ports to make stuff work is important, but should be done wisely for sure.

Other projects to keep in mind:
- https://codeberg.org/crabjail
- https://github.com/rusty-snake/firejail-profile-builder
- https://codeberg.org/rusty-snake/firefox-config and https://github.com/chiraag-nataraj/firejail-profiles
- https://github.com/rusty-snake/firejailed-tor-browser
- https://github.com/rusty-snake/kyst/ and other sandboxing presets
- https://github.com/rusty-snake/fireurl
- https://github.com/hardcore-sushi/TorVirt
- https://github.com/89luca89/distrobox/blob/main/docs/posts/run_libvirt_in_distrobox.md
- https://subgraph.com/sgos/
- https://codeberg.org/rps/fireinvoke
- https://codeberg.org/rps/fire-install (using fireinvoke)
- https://github.com/pigmonkey/firewarden
- https://easyos.org/about/how-and-why-easyos-is-different.html
- https://snyk.io/blog/best-practices-for-container-isolation/

**Comment by RoyalOughtness** [comment]
Thanks for your comments. I'll respond to them individually:

> Please note that Madaidans Article is now pretty old. Many issues still persist, but 3 or so of the linked ones where closed 5mo ago, due to being solved.

Regardless, that article is not the only reference point here. See also the grapheneos article https://grapheneos.org/usage#web-browsing

This project will not switch to firefox unless/until GrapheneOS does.

> I tried the distro and I am very thankful for your efford!

Thanks, though do note that technically this isn't a distro. The distro is still Fedora :)

> But I too have a problem with its usability.
> 
> It is not clear if these user namespaces are still a real problem. [In this thread](https://github.com/containers/podman/issues/20720) two Podman developers said that they don't see it as a security risk. Do with that what you want, these where not yet in depth answers, but just so you know.

Aside from the fact that Podman devs aren't the ultimate source of truth here, that isn't an accurate summary of what they said. They acknowledged a limited source of risk.

The real solution here is to use [bubblewrap-suid ](https://archlinux.org/packages/extra/x86_64/bubblewrap-suid/)and then re-enable flatpak. But that will require it to be built, packaged, and copr'd.

> Flatpak uses Bubblejail, which ironically Madaidan recommends. 

That's not correct, flatpak uses bubblewrap. Bubblejail is an experience on top of bubblewrap.

> Why disable it, how are users supposed to get their apps?

Because out of the box it depends on unprivileged usernamespaces, it can be reenabled in this project once we have a copr for bubblewrap-suid. It should be straightforward. If you want to work on it let me know and I can assign the Roadmap item to you.

> I see that this could be some kind of ChromeOS, 

The goals of this project are not like ChromeOS.

> * GIMP, Inkscape, Krita, ...

GIMP is already included in this project. If you want to add other default apps, please submit a pull request.

> Using Chromium or Electron for everything puts intense trust in Google 

No, it doesn't. They are both open-source projects. And all that is aside from the fact that anything "degoogle" related is out of scope for this project.

> Chrome will disable Adblocking soon, what then?

This is not accurate. MV2 support is going away, and that's a good thing. MV3's permissions model is significantly stronger and does not prevent adblocking. Ublock origin lite works well, and built-in adblockers like in brave work well also.


> But I see a privacy vs. Security issue here. One could say Thunderbird is less secure than some random webmail through Chromium. Or maybe some Electron app. But I suppose Thunderbird is local, very private and allows addons like Ublock.

Again, anything "privacy" related is not in-scope for this project. This project is about security, not privacy.


> In my eyes and the ones of other people, its better just to use noscript

Noscript has a massive usability impact and has more to do with "privacy" than security.

> have a hardened Firefox (which decreases the attack surface)

There isn't any amount of user.js tweaking that brings firefox up to par with chromium security.

> this is not Android/GrapheneOS

The stated goal above of this project is similar to GrapheneOS, so this is not accurate.

> So my ideas:
> 
> * keep firefox

This project will not switch to firefox unless/until GrapheneOS does.

> * keep flatpak

This will not be done unless/until we have a bubblewrap-suid copr available. If you are working on that please let me know and I'll assign you the ticket.

> * keep discover, remove the rpm-ostree backend as these go automatic and slow it down a lot

Not in scope, desirable, or possible. This indicates you don't understand what this project is about as it would not function without rpm-ostree. It's a set of images based on silverblue and kinoite. Without rpm-ostree, the images would not be installable, so your statement makes little sense.

> * if nix could work, this could be an alternative. But this involves having it in /var/nix and linking it to /nix or something similar, which may be out of scope

The nix installer is already available in the justfiles. Type "just" in the terminal

> Some other nice tools or settings to try out would be bubblejail and [SELinux Confined Users](https://fedoraproject.org/wiki/SELinux/ConfinedUsers), but this is a Desktop Task, I think GNOME works already? Plasma just seems to do weird things.

Bubblejail is a usability nightmare. Again, the solution here is to re-enable flatpak after including bubblewrap-suid via a copr:

https://github.com/orgs/secureblue/projects/1?pane=issue&itemId=45665263

**Comment by boredsquirrel** [comment]
Okay so I see your points

Discover would be used as a GUI store for installing Flatpaks, managing them, and also managing KDE plugins and firmware updates!

Do you think Vanadium patches can be directly applied to Chromium? This would indeed be very interesting. 

On KDE there also is QTWebEngine which uses a bundled Chromium. As a part of "Vanadium Webview" this would need to be replaced somehow too, probably needing a custom build of QtWebEngine with that hardened Chromum as a base.

bubblejail is just an extension for apps that dont work as Flatpaks well, everything integrating with the system etc.

I see that bubblewrap-suid is useful, and on Arch it worked just fine for Flatpaks. But as this doesnt even remotely exist for Podman, and I don't know the security implications against or for it, this would for now also decrease usability, as Distrobox is a huge plus for this Distro.

I will look at the rest. Thanks for your answers

**Comment by rusty-snake** [comment]
bubblewrap-suid is nothing more than but bubblewrap + `chown root:root` (better safe than sorry) + `chmod u+s`. 

Just pick https://src.fedoraproject.org/rpms/bubblewrap/blob/rawhide/f/bubblewrap.spec, add chown+chmod and change the name, description, ....

**Comment by wandapeter** [comment]
Hey! Thanks everyone for contributing in this discussion. :smile: 

@trytomakeyouprivate 

> It is not clear if these user namespaces are still a real problem. https://github.com/containers/podman/issues/20720 two Podman developers said that they don't see it as a security risk. Do with that what you want, these where not yet in depth answers, but just so you know.

https://www.cve.org/CVERecord?id=CVE-2022-0185

> I see that this could be some kind of ChromeOS, but this is simply not what normal (especially Linux) users use their Desktop like.

> keep discover, remove the rpm-ostree backend as these go automatic and slow it down a lot

Based on a immutable system (OSTree) does not mean you cannot install programs. Even if Flatpak will be disabled in this project, users can still install packages from `dnf` repositories as well as `copr` repositories va `rpm-ostree`. Apart from `rpm-ostree` being fundamental for this project to even work, keeping your system immutable decreases attack surface greatly an even opens up future possibilities like attestation akin to [Attestation App](https://attestation.app/about).

> keep flatpaks

I agree that for `secureblue` to be usable by a broader userbase some graphical installer needs to be present. Also, an immutable system and all installed apps running in their own sandbox is the best approach and OSTree along flatpak is the closest match on desktop Linux as of now. But i agree with @qoijjj  that `bubblewrap-suid` is probably the only approach since i also disagree with enabling unprivileged user namespaces. 

As for the browser issue:

@qoijjj 

I agree with sticking to chromium going further. But porting Vanadium seems like a task of immense complexity since the Vanadium patches done to Chromium like for instance disabling JIT V8 are Android Specific. But i do not know of any better solution. Maybe the easiest would be to just include Brave.

Also i think i would be interested in looking into creating the `bubblewrap-suid`  copr repository, but i do not have any experience working with rpm.

**Comment by wandapeter** [comment]
also: maybe move this to discussions?

**Comment by boredsquirrel** [comment]
@34N0 The idea is this: Discover is the GUI appstore. In theory you could use flathub.org, and install via terminal, but a GUI store seems better. Also as I said it handles plasma extensions and firmware updates, so it is important.

I wanted to find out a way to automate firmware updates since a while, because:
- they are damn important
- not included in automatic updates
- they always require a reboot (KDE 6 may be able to let apps block this until their work is closed, but until then this would mean random data loss)

So a system like on GrapheneOS for the updates would be needed:
- detection for metered connection (by default every connection is set to unmetered, so phone hotspot would be used!)
- detection of AC state
- detection of battery state at e.g. 50%
This could be done via a udev rule afaik, this enables a systemd target which is a dependency for automatic firmware updates to run.

If this is not working, a GUI appstore is needed.

I agree that an immutable system without layering might have advantages, even though I would not want to use it currently. But removing the extra packages "plasma-discover-rpm-ostree" and "gnome-software-rpm-ostree" would remove this ability from the GUI stores, remove annoying delays and allow users to only install flatpaks.

You could add the verified flathub repo:

```
flatpak remote-add --user --subset=verified flathub-verified https://flathub.org/repo/flathub.flatpakrepo
```

but this also lacks many apps currently, for example VLC, Brave, Element, QGis, Signal Desktop, Briar, Fluffychat, Pidgin, Inkscape, Calibre, Zotero, ...

I use KDE, but all these apply to GNOME too ofc

**Comment by RoyalOughtness** [comment]
> Okay so I see your points
> 
> Discover would be used as a GUI store for installing Flatpaks, managing them, and also managing KDE plugins and firmware updates!

Yes, discover can be added back after flatpaks are

> Do you think Vanadium patches can be directly applied to Chromium? This would indeed be very interesting.

Not all of them but some

**Comment by RoyalOughtness** [comment]
> also: maybe move this to discussions?

Instead, let's move each sub-conversation into the following tickets so we can split up and organize the conversations

bubblewrap-suid: https://github.com/secureblue/secureblue/issues/11
bubblejail: https://github.com/secureblue/secureblue/issues/22
chromium/vanadium: https://github.com/secureblue/secureblue/issues/14
usbguard: https://github.com/secureblue/secureblue/issues/15
grub hardening: https://github.com/secureblue/secureblue/issues/16
pam hardening: https://github.com/secureblue/secureblue/issues/17

I'll respond regarding each topic separately above and tag who I'm responding to. If there's any topic that's missing an issue, please open a new one.

Also, if you're working on any of these items, please tag me in the issue so there isn't duplicate work.

**Comment by RoyalOughtness** [comment]
@trytomakeyouprivate additionally, I've responded to you here: https://github.com/secureblue/secureblue/issues/26
